import re
import json

# Teacher full name to ID mapping
teacher_name_to_id = {
    'Hậu': 'gv_le_phuoc_hau',
    'Lụa': 'gv_nguyen_thi_lua',
    'Nhuận': 'gv_tran_van_nhuan',
    'Sang': 'gv_nguyen_thi_kim_sang',
    'Hiền Vi': 'gv_nguyen_hien_vi',
    'Điệp': 'gv_le_thi_ngoc_diep',
    'Thành': 'gv_le_minh_thanh',
    'Ngân': 'gv_nguyen_my_ngan',
    'Hà': 'gv_chau_thi_kim_ha',
    'NDiễm': 'gv_nguyen_thi_ngoc_diem',
    'Quốc': 'gv_tran_thi_my_quoc',
    'Tín': 'gv_nguyen_thanh_tin',
    'Văn': 'gv_nguyen_anh_van',
    'Nhi': 'gv_huynh_thi_van_nhi',
    'Tuyển': 'gv_le_thi_ngoc_tuyen',
    'Phương': 'gv_tran_kim_phuong',
    'Huy': 'gv_tran_quoc_huy',
    'Thảo': 'gv_nguyen_thi_thao',
    'Nga': 'gv_huynh_thi_huynh_nga',
    'Châu': 'gv_pham_thi_my_chau',
    'Chính': 'gv_le_van_chinh',
    'Bền': 'gv_truong_son_ben',
    'Tặt': 'gv_phan_van_tat',
    'Tiến': 'gv_thai_van_tien',
    'Đình Văn': 'gv_vo_ngoc_dinh_van',
    'Giàu': 'gv_dinh_thi_giau',
    'Tòng': 'gv_nguyen_thanh_tong',
    'Lâm': 'gv_pham_thanh_lam',
    'Thắm': 'gv_nguyen_thi_tham',
    'Tài': 'gv_ho_thi_ngoc_tai',
    'Lê Ngân': 'gv_le_kim_ngan',
    'Thái Hùng': 'gv_nguyen_thai_hung',
    'Thanh Hùng': 'gv_nguyen_thanh_hung',
    'Nguyễn Ngân': 'gv_nguyen_kim_ngan',
    'Lê Bình': 'gv_le_thi_binh',
    'Thủy': 'gv_le_hong_thuy',
    'Thúy': 'gv_le_hong_thuy',
    'Dương': 'gv_hua_thuy_duong',
    'văn-Dương': 'gv_hua_thuy_duong',
    'Tân': 'gv_nguyen_quoc_tan',
    'Quốc Tân': 'gv_nguyen_quoc_tan',
    'Lang': 'gv_nguyen_thi_bich_lang',
    'Xanh': 'gv_le_thi_tuyet_xanh',
    'Đạt': 'gv_le_minh_dat',
    'Nhung': 'gv_nguyen_thi_cam_nhung',
    'Hòa': 'gv_tran_phuoc_hoa',
    'Phước Hòa': 'gv_tran_phuoc_hoa',
    'Hiếu': 'gv_nguyen_thi_hieu',
    'Lê The': 'gv_le_thi_kim_the',
    'Kim The': 'gv_le_thi_kim_the',
    'Ngoan': 'gv_nguyen_van_ngoan',
    'Lộc': 'gv_mai_phuoc_loc',
    'Nguyễn': 'gv_nguyen_quoc_nguyen',
    'Ẩn': 'gv_le_ngoc_an',
    'Xoa': 'gv_nguyen_thi_kim_xoa',
    'Kim Xoa': 'gv_nguyen_thi_kim_xoa',
    'H Toàn': 'gv_vo_hoang_toan',
    'VToàn': 'gv_le_van_toan',
    'CToàn': 'gv_le_cao_toan',
    'Khanh': 'gv_nguyen_thi_mai_khanh',
    'Thùy Dương': 'gv_nguyen_thi_thuy_duong',
    'Giang': 'gv_tran_van_giang',
    'Tới': 'gv_nguyen_van_toi',
    'Cẩm': 'gv_tran_thi_cam',
    'Hải': 'gv_tran_phi_hai',
    'Hậu': 'gv_tran_thanh_hau', # context-dependent or HậuLP
    'Dân': 'gv_huynh_thanh_dan',
    'Thị Hậu': 'gv_tran_thi_hau',
    'Đỉnh': 'gv_nguyen_thi_kim_dinh',
    'Xe': 'gv_nguyen_thi_xe',
    'An': 'gv_le_thi_hoai_an',
    'Lý': 'gv_nguyen_thi_ly',
    'Sơn': 'gv_trinh_van_son',
    'Nghĩa': 'gv_truong_van_nghia',
    'Tùng': 'gv_cao_van_tung',
    'Kiều': 'gv_tran_thi_kieu',
    'Hiền': 'gv_tran_thi_ngoc_hien',
    'Trang': 'gv_nguyen_thi_be_trang',
    'Rạng': 'gv_nguyen_kim_rang',
    'Hương': 'gv_vo_thi_ngoc_huong',
    'Duyên': 'gv_truong_thi_my_duyen',
    'Nhịnh': 'gv_ho_van_nhinh',
    'Trường': 'gv_pham_nguyen_van_truong',
    'Ny': 'gv_le_thi_my_ny',
    'Thi': 'gv_vo_thi_hien_thi',
    'Thơ': 'gv_phan_thi_ngoc_tho',
    'Phi': 'gv_pham_long_phi',
    'Rỡ': 'gv_tran_van_ro',
    'Liên': 'gv_dao_thi_ngoc_lien',
    'Huỳnh': 'gv_bui_kim_huynh',
    'Lắm': 'gv_to_thi_lam',
    'Văn Anh': 'gv_nguyen_thi_van_anh',
    'Anh': 'gv_nguyen_thi_van_anh',
    'Hoài An': 'gv_le_thi_hoai_an',
    'Kim Sang': 'gv_nguyen_thi_kim_sang',
    'Thùy': 'gv_pham_bien_thuy',
    'Trí': 'gv_pht_tri',
    'Tuấn': 'gv_ngo_anh_tuan',
    'Nguyên': 'gv_le_van_nguyen',
    'Phướng': 'gv_bui_kim_phuong',
}

print(f"Loaded {len(teacher_name_to_id)} teacher name mappings.")
