import json
import re

# Campuses
CAMPUSES = [
    {
        "id": "THPTDBK",
        "name": "Điểm chính (THPT)",
        "code": "CS1-THPT",
        "address": "Số 12 Đường Lê Quý Đôn, Xã Đốc Binh Kiều, Tháp Mười, Đồng Tháp",
        "travelTimeMinutes": 15,
        "isMainCampus": True,
    },
    {
        "id": "THCSDBK",
        "name": "Điểm Đốc Binh Kiều (THCS)",
        "code": "CS2-THCS",
        "address": "Ấp 1, Xã Đốc Binh Kiều, Huyện Tháp Mười",
        "travelTimeMinutes": 20,
        "isMainCampus": False,
    },
    {
        "id": "THCSTK",
        "name": "Điểm Tân Kiều (THCS)",
        "code": "CS3-Tân Kiều",
        "address": "Xã Tân Kiều, Huyện Tháp Mười",
        "travelTimeMinutes": 30,
        "isMainCampus": False,
    },
]

# Teachers (101 teachers from user JSON/Markdown)
TEACHERS = [
    {"id": "tch-bgh-1", "name": "Lê Thanh Cường", "code": "Cường.LT (HT)", "departmentId": "dept-bgh", "campus": "THPTDBK", "isDualCampus": False},
    {"id": "tch-bgh-2", "name": "Nguyễn Minh Trí", "code": "Trí.NM (PHT)", "departmentId": "dept-bgh", "campus": "THPTDBK", "isDualCampus": False},
    {"id": "tch-bgh-3", "name": "Phan Thanh Thảo", "code": "Thảo.PT (PHT)", "departmentId": "dept-bgh", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-bgh-4", "name": "Nguyễn Thanh Tòng", "code": "Tòng.NT (PHT)", "departmentId": "dept-bgh", "campus": "THCSTK", "isDualCampus": False},
    {"id": "tch-t-1", "name": "Nguyễn Văn Tới", "code": "Tới.NV (TT)", "departmentId": "dept-toan", "campus": "THPTDBK", "isDualCampus": False},
    {"id": "tch-t-2", "name": "Trần Quốc Huy", "code": "Huy.TQ (9A7)", "departmentId": "dept-toan", "campus": "THCSTK", "isDualCampus": False},
    {"id": "tch-t-3", "name": "Nguyễn Thị Bích Lang", "code": "Lang.NTB (9A3)", "departmentId": "dept-toan", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-t-4", "name": "Trần Văn Giang", "code": "Giang.TV", "departmentId": "dept-toan", "campus": "THPTDBK", "isDualCampus": False},
    {"id": "tch-t-5", "name": "Lê Cao Toàn", "code": "Toàn.LC", "departmentId": "dept-toan", "campus": "THPTDBK", "isDualCampus": False},
    {"id": "tch-t-6", "name": "Lê Văn Toàn", "code": "Toàn.LV", "departmentId": "dept-toan", "campus": "THPTDBK", "isDualCampus": False},
    {"id": "tch-t-7", "name": "Võ Thị Ngọc Hương", "code": "Hương.VTN (12CB3)", "departmentId": "dept-toan", "campus": "THPTDBK", "isDualCampus": False},
    {"id": "tch-t-8", "name": "Lê Thị Bình", "code": "Bình.LT (6A6)", "departmentId": "dept-toan", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-t-9", "name": "Nguyễn Thái Hùng", "code": "Hùng.NThái (8A1)", "departmentId": "dept-toan", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-t-10", "name": "Nguyễn Văn Ngoan", "code": "Ngoan.NV (7A1)", "departmentId": "dept-toan", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-t-11", "name": "Nguyễn Quốc Nguyễn", "code": "Nguyễn.NQ (7A3)", "departmentId": "dept-toan", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-t-12", "name": "Nguyễn Văn Tài", "code": "Tài.NV (9A4)", "departmentId": "dept-toan", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-t-13", "name": "Nguyễn Thành Tín", "code": "Tín.NT (9A10)", "departmentId": "dept-toan", "campus": "THCSTK", "isDualCampus": False},
    {"id": "tch-t-14", "name": "Huỳnh Thị Huỳnh Nga", "code": "Nga.HTH", "departmentId": "dept-toan", "campus": "THCSTK", "isDualCampus": False},
    {"id": "tch-t-15", "name": "Trần Văn Nhuận", "code": "Nhuận.TV (8A10)", "departmentId": "dept-toan", "campus": "THCSTK", "isDualCampus": False},
    {"id": "tch-v-1", "name": "Tô Thị Lắm", "code": "Lắm.TT", "departmentId": "dept-ngu-van", "campus": "THPTDBK", "isDualCampus": False},
    {"id": "tch-v-2", "name": "Trương Văn Nghĩa", "code": "Nghĩa.TV", "departmentId": "dept-ngu-van", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-v-3", "name": "Huỳnh Thị Vân Nhi", "code": "Nhi.HTV", "departmentId": "dept-ngu-van", "campus": "THCSTK", "isDualCampus": False},
    {"id": "tch-v-4", "name": "Hồ Văn Nhịnh", "code": "Nhịnh.HV (10CB5)", "departmentId": "dept-ngu-van", "campus": "THPTDBK", "isDualCampus": False},
    {"id": "tch-v-5", "name": "Lê Thị Mỹ Ny", "code": "Ny.LTM (10CB3)", "departmentId": "dept-ngu-van", "campus": "THPTDBK", "isDualCampus": False},
    {"id": "tch-v-6", "name": "Trương Thị Mỹ Duyên", "code": "Duyên.TTM (12CB2)", "departmentId": "dept-ngu-van", "campus": "THPTDBK", "isDualCampus": False},
    {"id": "tch-v-8", "name": "Phạm Thanh Lâm", "code": "Lâm.PT", "departmentId": "dept-ngu-van", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-v-9", "name": "Nguyễn Thị Kim Xoa", "code": "Xoa.NTK", "departmentId": "dept-ngu-van", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-v-10", "name": "Hứa Thùy Dương", "code": "Dương.HT", "departmentId": "dept-ngu-van", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-v-11", "name": "Lê Thị Hoài An", "code": "An.LTH", "departmentId": "dept-ngu-van", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-v-13", "name": "Nguyễn Thị Thảo", "code": "Thảo.NT", "departmentId": "dept-ngu-van", "campus": "THCSTK", "isDualCampus": False},
    {"id": "tch-v-tk-vi", "name": "Nguyễn Hiền Vi", "code": "Vi.NH", "departmentId": "dept-ngu-van", "campus": "THCSTK", "isDualCampus": False},
    {"id": "tch-ls-1", "name": "Lê Hồng Thúy", "code": "Thúy.LH", "departmentId": "dept-khxh", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-ls-2", "name": "Trịnh Văn Sơn", "code": "Sơn.TV (12CB5)", "departmentId": "dept-khxh", "campus": "THPTDBK", "isDualCampus": False},
    {"id": "tch-ls-3", "name": "Phạm Thị Mỹ Châu", "code": "Châu.PTM (7A8)", "departmentId": "dept-khxh", "campus": "THCSTK", "isDualCampus": False},
    {"id": "tch-ls-4", "name": "Nguyễn Thị Bé Trang", "code": "Trang.NTB (12CB4)", "departmentId": "dept-khxh", "campus": "THPTDBK", "isDualCampus": False},
    {"id": "tch-ls-5", "name": "Trần Văn Rỡ", "code": "Rỡ.TV (11CB3)", "departmentId": "dept-khxh", "campus": "THPTDBK", "isDualCampus": False},
    {"id": "tch-ls-6", "name": "Trần Phước Hòa", "code": "Hòa.TP", "departmentId": "dept-khxh", "campus": "THPTDBK", "isDualCampus": False},
    {"id": "tch-ls-7", "name": "Ngô Anh Tuấn", "code": "Tuấn.NA", "departmentId": "dept-khxh", "campus": "THPTDBK", "isDualCampus": False},
    {"id": "tch-ls-8", "name": "Phạm Nguyễn Văn Trường", "code": "Trường.PNV", "departmentId": "dept-khxh", "campus": "THPTDBK", "isDualCampus": False},
    {"id": "tch-ls-9", "name": "Lê Thị Kim The", "code": "The.LTK", "departmentId": "dept-khxh", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-ls-10", "name": "Nguyễn Quốc Tấn", "code": "Tấn.NQ", "departmentId": "dept-khxh", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-ls-11", "name": "Nguyễn Thị Kim Đỉnh", "code": "Đỉnh.NTK", "departmentId": "dept-khxh", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-ls-12", "name": "Nguyễn Thị Lý", "code": "Lý.NT", "departmentId": "dept-khxh", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-ls-13", "name": "Nguyễn Thị Xe", "code": "Xe.NT", "departmentId": "dept-khxh", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-ls-14", "name": "Châu Thị Kim Hà", "code": "Hà.CTK", "departmentId": "dept-khxh", "campus": "THCSTK", "isDualCampus": False},
    {"id": "tch-ls-15", "name": "Nguyễn Thị Kim Sang", "code": "Sang.NTK (6A7)", "departmentId": "dept-khxh", "campus": "THCSTK", "isDualCampus": False},
    {"id": "tch-ls-16", "name": "Nguyễn Mỹ Ngân", "code": "Ngân.NM (9A9)", "departmentId": "dept-khxh", "campus": "THCSTK", "isDualCampus": False},
    {"id": "tch-khtn-1", "name": "Bùi Kim Huỳnh", "code": "Huỳnh.BK (11CB1)", "departmentId": "dept-khtn", "campus": "THPTDBK", "isDualCampus": False},
    {"id": "tch-khtn-2", "name": "Thái Văn Tiến", "code": "Tiến.TV (8A7)", "departmentId": "dept-khtn", "campus": "THCSTK", "isDualCampus": False},
    {"id": "tch-khtn-3", "name": "Phạm Biên Thùy", "code": "Thùy.PB", "departmentId": "dept-khtn", "campus": "THPTDBK", "isDualCampus": False},
    {"id": "tch-khtn-4", "name": "Nguyễn Thị Hiếu", "code": "Hiếu.NT (7A5)", "departmentId": "dept-khtn", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-khtn-5", "name": "Cao Văn Tùng", "code": "Tùng.CV (10CB1)", "departmentId": "dept-khtn", "campus": "THPTDBK", "isDualCampus": False},
    {"id": "tch-khtn-6", "name": "Trần Thị Ngọc Hiền", "code": "Hiền.TTN", "departmentId": "dept-khtn", "campus": "THPTDBK", "isDualCampus": False},
    {"id": "tch-khtn-7", "name": "Phan Thị Ngọc Thơ", "code": "Thơ.PTN (12CB1)", "departmentId": "dept-khtn", "campus": "THPTDBK", "isDualCampus": False},
    {"id": "tch-khtn-8", "name": "Phạm Long Phi", "code": "Phi.PL (11CB2)", "departmentId": "dept-khtn", "campus": "THPTDBK", "isDualCampus": False},
    {"id": "tch-khtn-9", "name": "Trần Thị Kiều", "code": "Kiều.TT (10CB2)", "departmentId": "dept-khtn", "campus": "THPTDBK", "isDualCampus": False},
    {"id": "tch-khtn-10", "name": "Trần Thị Hậu", "code": "Hậu.TTH (9A2)", "departmentId": "dept-khtn", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-khtn-11", "name": "Lê Thái Phương", "code": "Phương.LT (9A6)", "departmentId": "dept-khtn", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-khtn-12", "name": "Võ Hoàng Toàn", "code": "Toàn.VH (8A5)", "departmentId": "dept-khtn", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-khtn-13", "name": "Nguyễn Thị Thắm", "code": "Thắm.NT (6A2)", "departmentId": "dept-khtn", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-khtn-14", "name": "Nguyễn Thị Bích Phượng", "code": "Phượng.NTB (8A8)", "departmentId": "dept-khtn", "campus": "THCSTK", "isDualCampus": False},
    {"id": "tch-khtn-15", "name": "Võ Ngọc Đình Văn", "code": "Văn.VNĐ", "departmentId": "dept-khtn", "campus": "THCSTK", "isDualCampus": False},
    {"id": "tch-khtn-16", "name": "Nguyễn Thị Cẩm Nhung", "code": "Nhung.NTC (9A1)", "departmentId": "dept-khtn", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-khtn-17", "name": "Nguyễn Kim Ngân", "code": "Ngân.NK (8A4)", "departmentId": "dept-khtn", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-khtn-18", "name": "Hồ Thị Ngọc Tài", "code": "Tài.HTN (6A1)", "departmentId": "dept-khtn", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-khtn-19", "name": "Trần Kim Phương", "code": "Phương.TK (7A7)", "departmentId": "dept-khtn", "campus": "THCSTK", "isDualCampus": False},
    {"id": "tch-khtn-20", "name": "Đinh Thị Giàu", "code": "Giàu.ĐT (9A8)", "departmentId": "dept-khtn", "campus": "THCSTK", "isDualCampus": False},
    {"id": "tch-khtn-21", "name": "Nguyễn Thị Lụa", "code": "Lụa.NT (6A10)", "departmentId": "dept-khtn", "campus": "THCSTK", "isDualCampus": False},
    {"id": "tch-khtn-22", "name": "Trần Phi Hải", "code": "Hải.TP (8A2)", "departmentId": "dept-khtn", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-khtn-23", "name": "Trần Thị Cẩm", "code": "Cẩm.TT (7A6)", "departmentId": "dept-khtn", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-khtn-24", "name": "Lê Kim Ngân", "code": "Ngân.LK (6A5)", "departmentId": "dept-khtn", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-khtn-25", "name": "Nguyễn Thị Ngọc Diễm", "code": "Diễm.NTN (6A9)", "departmentId": "dept-khtn", "campus": "THCSTK", "isDualCampus": False},
    {"id": "tch-khtn-26", "name": "Phan Văn Tặt", "code": "Tặt.PV", "departmentId": "dept-khtn", "campus": "THCSTK", "isDualCampus": False},
    {"id": "tch-av-1", "name": "Lê Thị Ngọc Tuyền", "code": "Tuyền.LTN", "departmentId": "dept-tieng-anh-tin", "campus": "THCSTK", "isDualCampus": False},
    {"id": "tch-av-2", "name": "Nguyễn Trung Hiếu", "code": "Hiếu.NT (Tin)", "departmentId": "dept-tieng-anh-tin", "campus": "THPTDBK", "isDualCampus": False},
    {"id": "tch-av-3", "name": "Nguyễn Thị Mai Khanh", "code": "Khanh.NTM", "departmentId": "dept-tieng-anh-tin", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-av-4", "name": "Võ Thị Hiền Thi", "code": "Thi.VTH", "departmentId": "dept-tieng-anh-tin", "campus": "THPTDBK", "isDualCampus": False},
    {"id": "tch-av-5", "name": "Ngô Bảo Quốc", "code": "Quốc.NB", "departmentId": "dept-tieng-anh-tin", "campus": "THPTDBK", "isDualCampus": False},
    {"id": "tch-av-6", "name": "Trương Sơn Bền", "code": "Bền.TS", "departmentId": "dept-tieng-anh-tin", "campus": "THPTDBK", "isDualCampus": False},
    {"id": "tch-av-7", "name": "Nguyễn Thị Vân Anh", "code": "Anh.NTV", "departmentId": "dept-tieng-anh-tin", "campus": "THPTDBK", "isDualCampus": False},
    {"id": "tch-av-8", "name": "Đào Thị Ngọc Liên", "code": "Liên.ĐTN (11CB4)", "departmentId": "dept-tieng-anh-tin", "campus": "THPTDBK", "isDualCampus": False},
    {"id": "tch-av-9", "name": "Lê Thị Thu Diễm", "code": "Diễm.LTT (10CB4)", "departmentId": "dept-tieng-anh-tin", "campus": "THPTDBK", "isDualCampus": False},
    {"id": "tch-av-10", "name": "Trần Thanh Hậu", "code": "Hậu.TT", "departmentId": "dept-tieng-anh-tin", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-av-11", "name": "Hồ Mai Thảo", "code": "Thảo.HM (9A5)", "departmentId": "dept-tieng-anh-tin", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-av-12", "name": "Nguyễn Thị Thùy Dương", "code": "Dương.NTT (8A3)", "departmentId": "dept-tieng-anh-tin", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-av-13", "name": "Mai Phước Lộc", "code": "Lộc.MP (7A2)", "departmentId": "dept-tieng-anh-tin", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-av-14", "name": "Bùi Kim Phướng", "code": "Phướng.BK (6A3)", "departmentId": "dept-tieng-anh-tin", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-av-15", "name": "Lê Minh Thành", "code": "Thành.LM", "departmentId": "dept-tieng-anh-tin", "campus": "THCSTK", "isDualCampus": False},
    {"id": "tch-av-16", "name": "Lê Phước Hậu", "code": "Hậu.LP (8A9)", "departmentId": "dept-tieng-anh-tin", "campus": "THCSTK", "isDualCampus": False},
    {"id": "tch-td-1", "name": "Lê Văn Nguyên", "code": "Nguyên.LV", "departmentId": "dept-gdtc-qpan-nt", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-td-2", "name": "Nguyễn Kim Rạng", "code": "Rạng.NK", "departmentId": "dept-gdtc-qpan-nt", "campus": "THPTDBK", "isDualCampus": False},
    {"id": "tch-td-3", "name": "Lê Thị Ngọc Điệp", "code": "Điệp.LTN (6A8)", "departmentId": "dept-gdtc-qpan-nt", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-td-4", "name": "Hồ Hoài Ngân", "code": "Ngân.HH", "departmentId": "dept-gdtc-qpan-nt", "campus": "THPTDBK", "isDualCampus": False},
    {"id": "tch-td-5", "name": "Lê Minh Đạt", "code": "Đạt.LM", "departmentId": "dept-gdtc-qpan-nt", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-td-6", "name": "Lê Ngọc Ẩn", "code": "Ẩn.LN (7A4)", "departmentId": "dept-gdtc-qpan-nt", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-td-7", "name": "Huỳnh Thanh Dân", "code": "Dân.HT (8A6)", "departmentId": "dept-gdtc-qpan-nt", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-td-8", "name": "Nguyễn Thanh Hùng", "code": "Hùng.NThanh (6A4)", "departmentId": "dept-gdtc-qpan-nt", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-td-9", "name": "Lê Thị Tuyết Xanh", "code": "Xanh.LTT", "departmentId": "dept-gdtc-qpan-nt", "campus": "THCSDBK", "isDualCampus": False},
    {"id": "tch-td-10", "name": "Trần Thị Mỹ Quốc", "code": "Quốc.TTM", "departmentId": "dept-gdtc-qpan-nt", "campus": "THCSTK", "isDualCampus": False},
    {"id": "tch-td-11", "name": "Lê Văn Chính", "code": "Chính.LV (7A9)", "departmentId": "dept-gdtc-qpan-nt", "campus": "THCSTK", "isDualCampus": False},
    {"id": "tch-td-12", "name": "Nguyễn Anh Văn", "code": "Văn.NA", "departmentId": "dept-gdtc-qpan-nt", "campus": "THCSTK", "isDualCampus": False},
]

# Classes (53 classes from user JSON/Markdown)
CLASSES = [
    {"id": "cls-10cb1", "name": "10CB1", "grade": 10, "level": "THPT", "session": "SANG", "campus": "THPTDBK", "homeroomTeacherId": "tch-khtn-5"},
    {"id": "cls-10cb2", "name": "10CB2", "grade": 10, "level": "THPT", "session": "SANG", "campus": "THPTDBK", "homeroomTeacherId": "tch-khtn-9"},
    {"id": "cls-10cb3", "name": "10CB3", "grade": 10, "level": "THPT", "session": "SANG", "campus": "THPTDBK", "homeroomTeacherId": "tch-v-5"},
    {"id": "cls-10cb4", "name": "10CB4", "grade": 10, "level": "THPT", "session": "SANG", "campus": "THPTDBK", "homeroomTeacherId": "tch-av-9"},
    {"id": "cls-10cb5", "name": "10CB5", "grade": 10, "level": "THPT", "session": "SANG", "campus": "THPTDBK", "homeroomTeacherId": "tch-v-4"},
    {"id": "cls-11cb1", "name": "11CB1", "grade": 11, "level": "THPT", "session": "SANG", "campus": "THPTDBK", "homeroomTeacherId": "tch-khtn-1"},
    {"id": "cls-11cb2", "name": "11CB2", "grade": 11, "level": "THPT", "session": "SANG", "campus": "THPTDBK", "homeroomTeacherId": "tch-khtn-8"},
    {"id": "cls-11cb3", "name": "11CB3", "grade": 11, "level": "THPT", "session": "SANG", "campus": "THPTDBK", "homeroomTeacherId": "tch-ls-5"},
    {"id": "cls-11cb4", "name": "11CB4", "grade": 11, "level": "THPT", "session": "SANG", "campus": "THPTDBK", "homeroomTeacherId": "tch-av-8"},
    {"id": "cls-12cb1", "name": "12CB1", "grade": 12, "level": "THPT", "session": "SANG", "campus": "THPTDBK", "homeroomTeacherId": "tch-khtn-7"},
    {"id": "cls-12cb2", "name": "12CB2", "grade": 12, "level": "THPT", "session": "SANG", "campus": "THPTDBK", "homeroomTeacherId": "tch-v-6"},
    {"id": "cls-12cb3", "name": "12CB3", "grade": 12, "level": "THPT", "session": "SANG", "campus": "THPTDBK", "homeroomTeacherId": "tch-t-7"},
    {"id": "cls-12cb4", "name": "12CB4", "grade": 12, "level": "THPT", "session": "SANG", "campus": "THPTDBK", "homeroomTeacherId": "tch-ls-4"},
    {"id": "cls-12cb5", "name": "12CB5", "grade": 12, "level": "THPT", "session": "SANG", "campus": "THPTDBK", "homeroomTeacherId": "tch-ls-2"},
    {"id": "cls-6a1", "name": "6A1", "grade": 6, "level": "THCS", "session": "CHIEU", "campus": "THCSDBK", "homeroomTeacherId": "tch-khtn-18"},
    {"id": "cls-6a2", "name": "6A2", "grade": 6, "level": "THCS", "session": "CHIEU", "campus": "THCSDBK", "homeroomTeacherId": "tch-khtn-13"},
    {"id": "cls-6a3", "name": "6A3", "grade": 6, "level": "THCS", "session": "CHIEU", "campus": "THCSDBK", "homeroomTeacherId": "tch-av-14"},
    {"id": "cls-6a4", "name": "6A4", "grade": 6, "level": "THCS", "session": "CHIEU", "campus": "THCSDBK", "homeroomTeacherId": "tch-td-8"},
    {"id": "cls-6a5", "name": "6A5", "grade": 6, "level": "THCS", "session": "CHIEU", "campus": "THCSDBK", "homeroomTeacherId": "tch-khtn-24"},
    {"id": "cls-6a6", "name": "6A6", "grade": 6, "level": "THCS", "session": "CHIEU", "campus": "THCSDBK", "homeroomTeacherId": "tch-t-8"},
    {"id": "cls-6a7", "name": "6A7", "grade": 6, "level": "THCS", "session": "CHIEU", "campus": "THCSTK", "homeroomTeacherId": "tch-ls-15"},
    {"id": "cls-6a8", "name": "6A8", "grade": 6, "level": "THCS", "session": "CHIEU", "campus": "THCSTK", "homeroomTeacherId": "tch-td-3"},
    {"id": "cls-6a9", "name": "6A9", "grade": 6, "level": "THCS", "session": "CHIEU", "campus": "THCSTK", "homeroomTeacherId": "tch-khtn-25"},
    {"id": "cls-6a10", "name": "6A10", "grade": 6, "level": "THCS", "session": "CHIEU", "campus": "THCSTK", "homeroomTeacherId": "tch-khtn-21"},
    {"id": "cls-7a1", "name": "7A1", "grade": 7, "level": "THCS", "session": "CHIEU", "campus": "THCSDBK", "homeroomTeacherId": "tch-t-10"},
    {"id": "cls-7a2", "name": "7A2", "grade": 7, "level": "THCS", "session": "CHIEU", "campus": "THCSDBK", "homeroomTeacherId": "tch-av-13"},
    {"id": "cls-7a3", "name": "7A3", "grade": 7, "level": "THCS", "session": "CHIEU", "campus": "THCSDBK", "homeroomTeacherId": "tch-t-11"},
    {"id": "cls-7a4", "name": "7A4", "grade": 7, "level": "THCS", "session": "CHIEU", "campus": "THCSDBK", "homeroomTeacherId": "tch-td-6"},
    {"id": "cls-7a5", "name": "7A5", "grade": 7, "level": "THCS", "session": "CHIEU", "campus": "THCSDBK", "homeroomTeacherId": "tch-khtn-4"},
    {"id": "cls-7a6", "name": "7A6", "grade": 7, "level": "THCS", "session": "CHIEU", "campus": "THCSDBK", "homeroomTeacherId": "tch-khtn-23"},
    {"id": "cls-7a7", "name": "7A7", "grade": 7, "level": "THCS", "session": "CHIEU", "campus": "THCSTK", "homeroomTeacherId": "tch-khtn-19"},
    {"id": "cls-7a8", "name": "7A8", "grade": 7, "level": "THCS", "session": "CHIEU", "campus": "THCSTK", "homeroomTeacherId": "tch-ls-3"},
    {"id": "cls-7a9", "name": "7A9", "grade": 7, "level": "THCS", "session": "CHIEU", "campus": "THCSTK", "homeroomTeacherId": "tch-td-11"},
    {"id": "cls-8a1", "name": "8A1", "grade": 8, "level": "THCS", "session": "SANG", "campus": "THCSDBK", "homeroomTeacherId": "tch-t-9"},
    {"id": "cls-8a2", "name": "8A2", "grade": 8, "level": "THCS", "session": "SANG", "campus": "THCSDBK", "homeroomTeacherId": "tch-khtn-22"},
    {"id": "cls-8a3", "name": "8A3", "grade": 8, "level": "THCS", "session": "SANG", "campus": "THCSDBK", "homeroomTeacherId": "tch-ls-13"},
    {"id": "cls-8a4", "name": "8A4", "grade": 8, "level": "THCS", "session": "SANG", "campus": "THCSDBK", "homeroomTeacherId": "tch-khtn-17"},
    {"id": "cls-8a5", "name": "8A5", "grade": 8, "level": "THCS", "session": "SANG", "campus": "THCSDBK", "homeroomTeacherId": "tch-khtn-12"},
    {"id": "cls-8a6", "name": "8A6", "grade": 8, "level": "THCS", "session": "SANG", "campus": "THCSDBK", "homeroomTeacherId": "tch-td-7"},
    {"id": "cls-8a7", "name": "8A7", "grade": 8, "level": "THCS", "session": "SANG", "campus": "THCSTK", "homeroomTeacherId": "tch-khtn-2"},
    {"id": "cls-8a8", "name": "8A8", "grade": 8, "level": "THCS", "session": "SANG", "campus": "THCSTK", "homeroomTeacherId": "tch-khtn-14"},
    {"id": "cls-8a9", "name": "8A9", "grade": 8, "level": "THCS", "session": "SANG", "campus": "THCSTK", "homeroomTeacherId": "tch-av-16"},
    {"id": "cls-8a10", "name": "8A10", "grade": 8, "level": "THCS", "session": "SANG", "campus": "THCSTK", "homeroomTeacherId": "tch-t-15"},
    {"id": "cls-9a1", "name": "9A1", "grade": 9, "level": "THCS", "session": "SANG", "campus": "THCSDBK", "homeroomTeacherId": "tch-khtn-16"},
    {"id": "cls-9a2", "name": "9A2", "grade": 9, "level": "THCS", "session": "SANG", "campus": "THCSDBK", "homeroomTeacherId": "tch-khtn-10"},
    {"id": "cls-9a3", "name": "9A3", "grade": 9, "level": "THCS", "session": "SANG", "campus": "THCSDBK", "homeroomTeacherId": "tch-t-3"},
    {"id": "cls-9a4", "name": "9A4", "grade": 9, "level": "THCS", "session": "SANG", "campus": "THCSDBK", "homeroomTeacherId": "tch-t-12"},
    {"id": "cls-9a5", "name": "9A5", "grade": 9, "level": "THCS", "session": "SANG", "campus": "THCSDBK", "homeroomTeacherId": "tch-av-11"},
    {"id": "cls-9a6", "name": "9A6", "grade": 9, "level": "THCS", "session": "SANG", "campus": "THCSDBK", "homeroomTeacherId": "tch-khtn-11"},
    {"id": "cls-9a7", "name": "9A7", "grade": 9, "level": "THCS", "session": "SANG", "campus": "THCSTK", "homeroomTeacherId": "tch-t-2"},
    {"id": "cls-9a8", "name": "9A8", "grade": 9, "level": "THCS", "session": "SANG", "campus": "THCSTK", "homeroomTeacherId": "tch-khtn-20"},
    {"id": "cls-9a9", "name": "9A9", "grade": 9, "level": "THCS", "session": "SANG", "campus": "THCSTK", "homeroomTeacherId": "tch-ls-16"},
    {"id": "cls-9a10", "name": "9A10", "grade": 9, "level": "THCS", "session": "SANG", "campus": "THCSTK", "homeroomTeacherId": "tch-t-13"},
]

print(f"Loaded {len(CAMPUSES)} campuses, {len(TEACHERS)} teachers, {len(CLASSES)} classes.")
