# Part 2 of File 4 (501 to 1000)
with open('data_csv/timetable_file4_raw.csv', 'a', encoding='utf-8') as f:
    f.write('''"501","THCS_DocBinhKieu","6","6A3","4","Chieu","5","Ngữ văn","Hứa Thùy Dương","Dương.HT"
"502","THCS_DocBinhKieu","6","6A3","5","Chieu","1","Lịch sử và Địa lí","Nguyễn Quốc Tấn","Tấn.NQ"
"503","THCS_DocBinhKieu","6","6A3","5","Chieu","2","Lịch sử và Địa lí","Nguyễn Quốc Tấn","Tấn.NQ"
"504","THCS_DocBinhKieu","6","6A3","6","Chieu","1","Giáo dục công dân","Lê Hồng Thúy","Thúy.LH"
"505","THCS_DocBinhKieu","6","6A3","6","Chieu","2","Toán học","Nguyễn Thái Hùng","Hùng.NThái"
"506","THCS_DocBinhKieu","6","6A3","6","Chieu","3","Toán học","Nguyễn Thái Hùng","Hùng.NThái"
"507","THCS_DocBinhKieu","6","6A3","6","Chieu","4","Giáo dục thể chất","Nguyễn Thanh Hùng","Hùng.NThanh"
"508","THCS_DocBinhKieu","6","6A3","6","Chieu","5","Ngữ văn","Hứa Thùy Dương","Dương.HT"
"509","THCS_DocBinhKieu","6","6A3","7","Chieu","1","Công nghệ","Lê Kim Ngân","Ngân.LK"
"510","THCS_DocBinhKieu","6","6A3","7","Chieu","2","Khoa học tự nhiên","Nguyễn Kim Ngân","Ngân.NK"
"511","THCS_DocBinhKieu","6","6A3","7","Chieu","3","Tiếng Anh","Hồ Mai Thảo","Thảo.HM"
"512","THCS_DocBinhKieu","6","6A3","7","Chieu","4","Tiếng Anh","Hồ Mai Thảo","Thảo.HM"
"513","THCS_DocBinhKieu","6","6A3","7","Chieu","5","Sinh hoạt lớp","Bùi Kim Phướng","Phướng.BK"
"514","THCS_DocBinhKieu","6","6A4","2","Chieu","1","Toán học","Lê Thị Bình","Bình.LT"
"515","THCS_DocBinhKieu","6","6A4","2","Sang","1","HĐTNHN (Chuyên đề)","Nguyễn Thị Thắm","Thắm.NT"
"516","THCS_DocBinhKieu","6","6A4","2","Chieu","2","Khoa học tự nhiên","Nguyễn Kim Ngân","Ngân.NK"
"517","THCS_DocBinhKieu","6","6A4","2","Sang","2","HĐTNHN (Quy mô lớp)","Nguyễn Thanh Hùng","Hùng.NThanh"
"518","THCS_DocBinhKieu","6","6A4","2","Chieu","3","Khoa học tự nhiên","Nguyễn Kim Ngân","Ngân.NK"
"519","THCS_DocBinhKieu","6","6A4","2","Chieu","4","Giáo dục thể chất","Nguyễn Thanh Hùng","Hùng.NThanh"
"520","THCS_DocBinhKieu","6","6A4","2","Chieu","5","Chào cờ","Nguyễn Thanh Hùng","Hùng.NThanh"
"521","THCS_DocBinhKieu","6","6A4","3","Chieu","1","Tiếng Anh","Trần Thanh Hậu","Hậu.TT"
"522","THCS_DocBinhKieu","6","6A4","3","Chieu","2","Lịch sử và Địa lí","Nguyễn Quốc Tấn","Tấn.NQ"
"523","THCS_DocBinhKieu","6","6A4","3","Chieu","3","Mỹ thuật","Trần Thị Mỹ Quốc","Quốc.TTM"
"524","THCS_DocBinhKieu","6","6A4","3","Chieu","4","Giáo dục thể chất","Nguyễn Thanh Hùng","Hùng.NThanh"
"525","THCS_DocBinhKieu","6","6A4","3","Chieu","5","Ngữ văn","Phạm Thanh Lâm","Lâm.PT"
"526","THCS_DocBinhKieu","6","6A4","4","Chieu","1","Khoa học tự nhiên","Nguyễn Kim Ngân","Ngân.NK"
"527","THCS_DocBinhKieu","6","6A4","4","Chieu","2","Giáo dục công dân","Lê Hồng Thúy","Thúy.LH"
"528","THCS_DocBinhKieu","6","6A4","4","Chieu","3","Âm nhạc","Nguyễn Anh Văn","Văn.NA"
"529","THCS_DocBinhKieu","6","6A4","4","Chieu","4","Công nghệ","Lê Kim Ngân","Ngân.LK"
"530","THCS_DocBinhKieu","6","6A4","4","Chieu","5","Toán học","Lê Thị Bình","Bình.LT"
"531","THCS_DocBinhKieu","6","6A4","5","Chieu","1","Ngữ văn","Phạm Thanh Lâm","Lâm.PT"
"532","THCS_DocBinhKieu","6","6A4","5","Chieu","2","Ngữ văn","Phạm Thanh Lâm","Lâm.PT"
"533","THCS_DocBinhKieu","6","6A4","6","Chieu","1","Lịch sử và Địa lí","Nguyễn Quốc Tấn","Tấn.NQ"
"534","THCS_DocBinhKieu","6","6A4","6","Chieu","2","Lịch sử và Địa lí","Nguyễn Quốc Tấn","Tấn.NQ"
"535","THCS_DocBinhKieu","6","6A4","6","Chieu","3","Tiếng Anh","Trần Thanh Hậu","Hậu.TT"
"536","THCS_DocBinhKieu","6","6A4","6","Chieu","4","Tiếng Anh","Trần Thanh Hậu","Hậu.TT"
"537","THCS_DocBinhKieu","6","6A4","6","Chieu","5","Ngữ văn","Phạm Thanh Lâm","Lâm.PT"
"538","THCS_DocBinhKieu","6","6A4","7","Chieu","1","Tin học","Bùi Kim Phướng","Phướng.BK"
"539","THCS_DocBinhKieu","6","6A4","7","Chieu","2","Toán học","Lê Thị Bình","Bình.LT"
"540","THCS_DocBinhKieu","6","6A4","7","Chieu","3","Toán học","Lê Thị Bình","Bình.LT"
"541","THCS_DocBinhKieu","6","6A4","7","Chieu","4","Khoa học tự nhiên","Nguyễn Kim Ngân","Ngân.NK"
"542","THCS_DocBinhKieu","6","6A4","7","Chieu","5","Sinh hoạt lớp","Nguyễn Thanh Hùng","Hùng.NThanh"
"543","THCS_DocBinhKieu","6","6A5","2","Chieu","1","Khoa học tự nhiên","Nguyễn Kim Ngân","Ngân.NK"
"544","THCS_DocBinhKieu","6","6A5","2","Sang","1","HĐTNHN (Quy mô lớp)","Lê Kim Ngân","Ngân.LK"
"545","THCS_DocBinhKieu","6","6A5","2","Chieu","2","Toán học","Lê Thị Bình","Bình.LT"
"546","THCS_DocBinhKieu","6","6A5","2","Sang","2","HĐTNHN (Chuyên đề)","Lê Kim Ngân","Ngân.LK"
"547","THCS_DocBinhKieu","6","6A5","2","Chieu","3","Giáo dục thể chất","Nguyễn Thanh Hùng","Hùng.NThanh"
"548","THCS_DocBinhKieu","6","6A5","2","Chieu","4","Ngữ văn","Hứa Thùy Dương","Dương.HT"
"549","THCS_DocBinhKieu","6","6A5","2","Chieu","5","Chào cờ","Lê Kim Ngân","Ngân.LK"
"550","THCS_DocBinhKieu","6","6A5","3","Chieu","1","Giáo dục công dân","Lê Hồng Thúy","Thúy.LH"
"551","THCS_DocBinhKieu","6","6A5","3","Chieu","2","Toán học","Lê Thị Bình","Bình.LT"
"552","THCS_DocBinhKieu","6","6A5","3","Chieu","3","Tiếng Anh","Trần Thanh Hậu","Hậu.TT"
"553","THCS_DocBinhKieu","6","6A5","3","Chieu","4","Mỹ thuật","Trần Thị Mỹ Quốc","Quốc.TTM"
"554","THCS_DocBinhKieu","6","6A5","3","Chieu","5","Ngữ văn","Hứa Thùy Dương","Dương.HT"
"555","THCS_DocBinhKieu","6","6A5","4","Chieu","1","Toán học","Lê Thị Bình","Bình.LT"
"556","THCS_DocBinhKieu","6","6A5","4","Chieu","2","Toán học","Lê Thị Bình","Bình.LT"
"557","THCS_DocBinhKieu","6","6A5","4","Chieu","3","Lịch sử","Nguyễn Quốc Tấn","Tấn.NQ"
"558","THCS_DocBinhKieu","6","6A5","4","Chieu","4","Âm nhạc","Nguyễn Anh Văn","Văn.NA"
"559","THCS_DocBinhKieu","6","6A5","4","Chieu","5","Khoa học tự nhiên","Nguyễn Kim Ngân","Ngân.NK"
"560","THCS_DocBinhKieu","6","6A5","5","Chieu","1","Khoa học tự nhiên","Nguyễn Kim Ngân","Ngân.NK"
"561","THCS_DocBinhKieu","6","6A5","5","Chieu","2","Khoa học tự nhiên","Nguyễn Kim Ngân","Ngân.NK"
"562","THCS_DocBinhKieu","6","6A5","6","Chieu","1","Tiếng Anh","Trần Thanh Hậu","Hậu.TT"
"563","THCS_DocBinhKieu","6","6A5","6","Chieu","2","Tiếng Anh","Trần Thanh Hậu","Hậu.TT"
"564","THCS_DocBinhKieu","6","6A5","6","Chieu","3","Ngữ văn","Hứa Thùy Dương","Dương.HT"
"565","THCS_DocBinhKieu","6","6A5","6","Chieu","4","Ngữ văn","Hứa Thùy Dương","Dương.HT"
"566","THCS_DocBinhKieu","6","6A5","6","Chieu","5","Địa lí","Trần Phước Hòa","Hòa.TP"
"567","THCS_DocBinhKieu","6","6A5","7","Chieu","1","Lịch sử","Nguyễn Quốc Tấn","Tấn.NQ"
"568","THCS_DocBinhKieu","6","6A5","7","Chieu","2","Tin học","Bùi Kim Phướng","Phướng.BK"
"569","THCS_DocBinhKieu","6","6A5","7","Chieu","3","Công nghệ","Lê Kim Ngân","Ngân.LK"
"570","THCS_DocBinhKieu","6","6A5","7","Chieu","4","Giáo dục thể chất","Nguyễn Thanh Hùng","Hùng.NThanh"
"571","THCS_DocBinhKieu","6","6A5","7","Chieu","5","Sinh hoạt lớp","Lê Kim Ngân","Ngân.LK"
"572","THCS_DocBinhKieu","6","6A6","2","Chieu","1","Khoa học tự nhiên","Hồ Thị Ngọc Tài","Tài.HTN"
"573","THCS_DocBinhKieu","6","6A6","2","Chieu","2","Giáo dục thể chất","Nguyễn Thanh Hùng","Hùng.NThanh"
"574","THCS_DocBinhKieu","6","6A6","2","Chieu","3","Ngữ văn","Hứa Thùy Dương","Dương.HT"
"575","THCS_DocBinhKieu","6","6A6","2","Chieu","4","Toán học","Lê Thị Bình","Bình.LT"
"576","THCS_DocBinhKieu","6","6A6","2","Chieu","5","Chào cờ","Lê Thị Bình","Bình.LT"
"577","THCS_DocBinhKieu","6","6A6","3","Chieu","1","Toán học","Lê Thị Bình","Bình.LT"
"578","THCS_DocBinhKieu","6","6A6","3","Chieu","2","Giáo dục thể chất","Nguyễn Thanh Hùng","Hùng.NThanh"
"579","THCS_DocBinhKieu","6","6A6","3","Chieu","3","Lịch sử","Nguyễn Quốc Tấn","Tấn.NQ"
"580","THCS_DocBinhKieu","6","6A6","3","Chieu","4","Tiếng Anh","Trần Thanh Hậu","Hậu.TT"
"581","THCS_DocBinhKieu","6","6A6","3","Chieu","5","Mỹ thuật","Trần Thị Mỹ Quốc","Quốc.TTM"
"582","THCS_DocBinhKieu","6","6A6","4","Chieu","1","Khoa học tự nhiên","Hồ Thị Ngọc Tài","Tài.HTN"
"583","THCS_DocBinhKieu","6","6A6","4","Sang","1","HĐTNHN (Quy mô lớp)","Lê Thị Bình","Bình.LT"
"584","THCS_DocBinhKieu","6","6A6","4","Chieu","2","Khoa học tự nhiên","Hồ Thị Ngọc Tài","Tài.HTN"
"585","THCS_DocBinhKieu","6","6A6","4","Sang","2","HĐTNHN (Chuyên đề)","Lê Kim Ngân","Ngân.LK"
"586","THCS_DocBinhKieu","6","6A6","4","Chieu","3","Ngữ văn","Hứa Thùy Dương","Dương.HT"
"587","THCS_DocBinhKieu","6","6A6","4","Chieu","4","Ngữ văn","Hứa Thùy Dương","Dương.HT"
"588","THCS_DocBinhKieu","6","6A6","4","Chieu","5","Âm nhạc","Nguyễn Anh Văn","Văn.NA"
"589","THCS_DocBinhKieu","6","6A6","5","Chieu","1","Khoa học tự nhiên","Hồ Thị Ngọc Tài","Tài.HTN"
"590","THCS_DocBinhKieu","6","6A6","5","Chieu","2","Ngữ văn","Hứa Thùy Dương","Dương.HT"
"591","THCS_DocBinhKieu","6","6A6","6","Chieu","1","Toán học","Lê Thị Bình","Bình.LT"
"592","THCS_DocBinhKieu","6","6A6","6","Chieu","2","Toán học","Lê Thị Bình","Bình.LT"
"593","THCS_DocBinhKieu","6","6A6","6","Chieu","3","Giáo dục công dân","Lê Hồng Thúy","Thúy.LH"
"594","THCS_DocBinhKieu","6","6A6","6","Chieu","4","Địa lí","Trần Phước Hòa","Hòa.TP"
"595","THCS_DocBinhKieu","6","6A6","6","Chieu","5","Lịch sử","Nguyễn Quốc Tấn","Tấn.NQ"
"596","THCS_DocBinhKieu","6","6A6","7","Chieu","1","Tiếng Anh","Trần Thanh Hậu","Hậu.TT"
"597","THCS_DocBinhKieu","6","6A6","7","Chieu","2","Tiếng Anh","Trần Thanh Hậu","Hậu.TT"
"598","THCS_DocBinhKieu","6","6A6","7","Chieu","3","Tin học","Bùi Kim Phướng","Phướng.BK"
"599","THCS_DocBinhKieu","6","6A6","7","Chieu","4","Công nghệ","Lê Kim Ngân","Ngân.LK"
"600","THCS_DocBinhKieu","6","6A6","7","Chieu","5","Sinh hoạt lớp","Lê Thị Bình","Bình.LT"
"601","THCS_TanKieu","6","6A7","2","Chieu","1","Tin học","Lê Phước Hậu","Hậu.LP"
"602","THCS_TanKieu","6","6A7","2","Sang","1","HĐTNHN (Chuyên đề)","Nguyễn Thị Ngọc Diễm","Diễm.NTN"
"603","THCS_TanKieu","6","6A7","2","Chieu","2","Giáo dục công dân","Nguyễn Mỹ Ngân","Ngân.NM"
"604","THCS_TanKieu","6","6A7","2","Sang","2","HĐTNHN (Quy mô lớp)","Nguyễn Thị Ngọc Diễm","Diễm.NTN"
"605","THCS_TanKieu","6","6A7","2","Chieu","3","Ngữ văn","Nguyễn Hiền Vi","Vi.NH"
"606","THCS_TanKieu","6","6A7","2","Chieu","4","Ngữ văn","Nguyễn Hiền Vi","Vi.NH"
"607","THCS_TanKieu","6","6A7","2","Chieu","5","Chào cờ","Nguyễn Thị Kim Sang","Sang.NTK"
"608","THCS_TanKieu","6","6A7","3","Chieu","1","Ngữ văn","Nguyễn Hiền Vi","Vi.NH"
"609","THCS_TanKieu","6","6A7","3","Chieu","2","Khoa học tự nhiên","Nguyễn Thị Lụa","Lụa.NT"
"610","THCS_TanKieu","6","6A7","3","Chieu","3","Khoa học tự nhiên","Nguyễn Thị Lụa","Lụa.NT"
"611","THCS_TanKieu","6","6A7","3","Chieu","4","Công nghệ","Nguyễn Thị Ngọc Diễm","Diễm.NTN"
"612","THCS_TanKieu","6","6A7","3","Chieu","5","Tiếng Anh","Lê Minh Thành","Thành.LM"
"613","THCS_TanKieu","6","6A7","4","Chieu","1","Khoa học tự nhiên","Nguyễn Thị Lụa","Lụa.NT"
"614","THCS_TanKieu","6","6A7","4","Chieu","2","Lịch sử","Châu Thị Kim Hà","Hà.CTK"
"615","THCS_TanKieu","6","6A7","4","Chieu","3","Ngữ văn","Nguyễn Hiền Vi","Vi.NH"
"616","THCS_TanKieu","6","6A7","4","Chieu","4","Toán học","Trần Văn Nhuận","Nhuận.TV"
"617","THCS_TanKieu","6","6A7","4","Chieu","5","Toán học","Trần Văn Nhuận","Nhuận.TV"
"618","THCS_TanKieu","6","6A7","5","Chieu","1","Mỹ thuật","Trần Thị Mỹ Quốc","Quốc.TTM"
"619","THCS_TanKieu","6","6A7","5","Chieu","2","Toán học","Trần Văn Nhuận","Nhuận.TV"
"620","THCS_TanKieu","6","6A7","6","Chieu","1","Lịch sử","Châu Thị Kim Hà","Hà.CTK"
"621","THCS_TanKieu","6","6A7","6","Chieu","2","Khoa học tự nhiên","Nguyễn Thị Lụa","Lụa.NT"
"622","THCS_TanKieu","6","6A7","6","Chieu","3","Âm nhạc","Nguyễn Anh Văn","Văn.NA"
"623","THCS_TanKieu","6","6A7","6","Chieu","4","Tiếng Anh","Lê Minh Thành","Thành.LM"
"624","THCS_TanKieu","6","6A7","6","Chieu","5","Tiếng Anh","Lê Minh Thành","Thành.LM"
"625","THCS_TanKieu","6","6A7","7","Chieu","1","Địa lí","Nguyễn Thị Kim Sang","Sang.NTK"
"626","THCS_TanKieu","6","6A7","7","Chieu","2","Toán học","Trần Văn Nhuận","Nhuận.TV"
"627","THCS_TanKieu","6","6A7","7","Chieu","3","Giáo dục thể chất","Lê Thị Ngọc Điệp","Điệp.LTN"
"628","THCS_TanKieu","6","6A7","7","Chieu","4","Giáo dục thể chất","Lê Thị Ngọc Điệp","Điệp.LTN"
"629","THCS_TanKieu","6","6A7","7","Chieu","5","Sinh hoạt lớp","Nguyễn Thị Kim Sang","Sang.NTK"
"630","THCS_TanKieu","6","6A8","2","Chieu","1","Toán học","Trần Văn Nhuận","Nhuận.TV"
"631","THCS_TanKieu","6","6A8","2","Chieu","2","Toán học","Trần Văn Nhuận","Nhuận.TV"
"632","THCS_TanKieu","6","6A8","2","Chieu","3","Khoa học tự nhiên","Nguyễn Thị Lụa","Lụa.NT"
"633","THCS_TanKieu","6","6A8","2","Chieu","4","Địa lí","Nguyễn Thị Kim Sang","Sang.NTK"
"634","THCS_TanKieu","6","6A8","2","Chieu","5","Chào cờ","Lê Thị Ngọc Điệp","Điệp.LTN"
"635","THCS_TanKieu","6","6A8","3","Chieu","1","Giáo dục công dân","Nguyễn Mỹ Ngân","Ngân.NM"
"636","THCS_TanKieu","6","6A8","3","Sang","1","HĐTNHN (Chuyên đề)","Nguyễn Thị Ngọc Diễm","Diễm.NTN"
"637","THCS_TanKieu","6","6A8","3","Chieu","2","Tin học","Lê Phước Hậu","Hậu.LP"
"638","THCS_TanKieu","6","6A8","3","Sang","2","HĐTNHN (Quy mô lớp)","Nguyễn Thị Ngọc Diễm","Diễm.NTN"
"639","THCS_TanKieu","6","6A8","3","Chieu","3","Ngữ văn","Nguyễn Hiền Vi","Vi.NH"
"640","THCS_TanKieu","6","6A8","3","Chieu","4","Giáo dục thể chất","Lê Thị Ngọc Điệp","Điệp.LTN"
"641","THCS_TanKieu","6","6A8","3","Chieu","5","Giáo dục thể chất","Lê Thị Ngọc Điệp","Điệp.LTN"
"642","THCS_TanKieu","6","6A8","4","Chieu","1","Mỹ thuật","Trần Thị Mỹ Quốc","Quốc.TTM"
"643","THCS_TanKieu","6","6A8","4","Chieu","2","Khoa học tự nhiên","Nguyễn Thị Lụa","Lụa.NT"
"644","THCS_TanKieu","6","6A8","4","Chieu","3","Khoa học tự nhiên","Nguyễn Thị Lụa","Lụa.NT"
"645","THCS_TanKieu","6","6A8","4","Chieu","4","Ngữ văn","Nguyễn Hiền Vi","Vi.NH"
"646","THCS_TanKieu","6","6A8","4","Chieu","5","Ngữ văn","Nguyễn Hiền Vi","Vi.NH"
"647","THCS_TanKieu","6","6A8","5","Chieu","1","Toán học","Trần Văn Nhuận","Nhuận.TV"
"648","THCS_TanKieu","6","6A8","5","Chieu","2","Tiếng Anh","Lê Thị Ngọc Tuyền","Tuyền.LTN"
"649","THCS_TanKieu","6","6A8","6","Chieu","1","Âm nhạc","Nguyễn Anh Văn","Văn.NA"
"650","THCS_TanKieu","6","6A8","6","Chieu","2","Lịch sử","Châu Thị Kim Hà","Hà.CTK"
"651","THCS_TanKieu","6","6A8","6","Chieu","3","Khoa học tự nhiên","Nguyễn Thị Lụa","Lụa.NT"
"652","THCS_TanKieu","6","6A8","6","Chieu","4","Tiếng Anh","Lê Thị Ngọc Tuyền","Tuyền.LTN"
"653","THCS_TanKieu","6","6A8","6","Chieu","5","Tiếng Anh","Lê Thị Ngọc Tuyền","Tuyền.LTN"
"654","THCS_TanKieu","6","6A8","7","Chieu","1","Lịch sử","Châu Thị Kim Hà","Hà.CTK"
"655","THCS_TanKieu","6","6A8","7","Chieu","2","Ngữ văn","Nguyễn Hiền Vi","Vi.NH"
"656","THCS_TanKieu","6","6A8","7","Chieu","3","Toán học","Trần Văn Nhuận","Nhuận.TV"
"657","THCS_TanKieu","6","6A8","7","Chieu","4","Công nghệ","Nguyễn Thị Ngọc Diễm","Diễm.NTN"
"658","THCS_TanKieu","6","6A8","7","Chieu","5","Sinh hoạt lớp","Lê Thị Ngọc Điệp","Điệp.LTN"
"659","THCS_TanKieu","6","6A9","2","Chieu","1","Toán học","Nguyễn Thành Tín","Tín.NT"
"660","THCS_TanKieu","6","6A9","2","Chieu","2","Toán học","Nguyễn Thành Tín","Tín.NT"
"661","THCS_TanKieu","6","6A9","2","Chieu","3","Giáo dục thể chất","Lê Thị Ngọc Điệp","Điệp.LTN"
"662","THCS_TanKieu","6","6A9","2","Chieu","4","Giáo dục thể chất","Lê Thị Ngọc Điệp","Điệp.LTN"
"663","THCS_TanKieu","6","6A9","2","Chieu","5","Chào cờ","Nguyễn Thị Ngọc Diễm","Diễm.NTN"
"664","THCS_TanKieu","6","6A9","3","Chieu","1","Toán học","Nguyễn Thành Tín","Tín.NT"
"665","THCS_TanKieu","6","6A9","3","Chieu","2","Toán học","Nguyễn Thành Tín","Tín.NT"
"666","THCS_TanKieu","6","6A9","3","Chieu","3","Công nghệ","Nguyễn Thị Ngọc Diễm","Diễm.NTN"
"667","THCS_TanKieu","6","6A9","3","Chieu","4","Khoa học tự nhiên","Nguyễn Thị Bích Phượng","Phượng.NTB"
"668","THCS_TanKieu","6","6A9","3","Chieu","5","Khoa học tự nhiên","Nguyễn Thị Bích Phượng","Phượng.NTB"
"669","THCS_TanKieu","6","6A9","4","Chieu","1","Tin học","Lê Phước Hậu","Hậu.LP"
"670","THCS_TanKieu","6","6A9","4","Sang","1","HĐTNHN (Chuyên đề)","Nguyễn Thị Ngọc Diễm","Diễm.NTN"
"671","THCS_TanKieu","6","6A9","4","Chieu","2","Mỹ thuật","Trần Thị Mỹ Quốc","Quốc.TTM"
"672","THCS_TanKieu","6","6A9","4","Sang","2","HĐTNHN (Quy mô lớp)","Nguyễn Thị Ngọc Diễm","Diễm.NTN"
"673","THCS_TanKieu","6","6A9","4","Chieu","3","Khoa học tự nhiên","Nguyễn Thị Bích Phượng","Phượng.NTB"
"674","THCS_TanKieu","6","6A9","4","Chieu","4","Khoa học tự nhiên","Nguyễn Thị Bích Phượng","Phượng.NTB"
"675","THCS_TanKieu","6","6A9","4","Chieu","5","Giáo dục công dân","Nguyễn Mỹ Ngân","Ngân.NM"
"676","THCS_TanKieu","6","6A9","5","Chieu","1","Tiếng Anh","Lê Thị Ngọc Tuyền","Tuyền.LTN"
"677","THCS_TanKieu","6","6A9","5","Chieu","2","Âm nhạc","Nguyễn Anh Văn","Văn.NA"
"678","THCS_TanKieu","6","6A9","6","Chieu","1","Tiếng Anh","Lê Thị Ngọc Tuyền","Tuyền.LTN"
"679","THCS_TanKieu","6","6A9","6","Chieu","2","Tiếng Anh","Lê Thị Ngọc Tuyền","Tuyền.LTN"
"680","THCS_TanKieu","6","6A9","6","Chieu","3","Lịch sử","Châu Thị Kim Hà","Hà.CTK"
"681","THCS_TanKieu","6","6A9","6","Chieu","4","Ngữ văn","Huỳnh Thị Vân Nhi","Nhi.HTV"
"682","THCS_TanKieu","6","6A9","6","Chieu","5","Ngữ văn","Huỳnh Thị Vân Nhi","Nhi.HTV"
"683","THCS_TanKieu","6","6A9","7","Chieu","1","Ngữ văn","Huỳnh Thị Vân Nhi","Nhi.HTV"
"684","THCS_TanKieu","6","6A9","7","Chieu","2","Ngữ văn","Huỳnh Thị Vân Nhi","Nhi.HTV"
"685","THCS_TanKieu","6","6A9","7","Chieu","3","Lịch sử","Châu Thị Kim Hà","Hà.CTK"
"686","THCS_TanKieu","6","6A9","7","Chieu","4","Địa lí","Nguyễn Thị Kim Sang","Sang.NTK"
"687","THCS_TanKieu","6","6A9","7","Chieu","5","Sinh hoạt lớp","Nguyễn Thị Ngọc Diễm","Diễm.NTN"
"688","THCS_DocBinhKieu","7","7A1","2","Chieu","1","Giáo dục công dân","Lê Hồng Thúy","Thúy.LH"
"689","THCS_DocBinhKieu","7","7A1","2","Sang","1","HĐTNHN (Quy mô lớp)","Nguyễn Văn Ngoan","Ngoan.NV"
"690","THCS_DocBinhKieu","7","7A1","2","Chieu","2","Địa lí","Nguyễn Thị Kim Đỉnh","Đỉnh.NTK"
"691","THCS_DocBinhKieu","7","7A1","2","Sang","2","HĐTNHN (Chuyên đề)","Bùi Kim Phướng","Phướng.BK"
"692","THCS_DocBinhKieu","7","7A1","2","Chieu","3","Khoa học tự nhiên","Nguyễn Thị Hiếu","Hiếu.NT"
"693","THCS_DocBinhKieu","7","7A1","2","Chieu","4","Toán học","Nguyễn Văn Ngoan","Ngoan.NV"
"694","THCS_DocBinhKieu","7","7A1","2","Chieu","5","Chào cờ","Nguyễn Văn Ngoan","Ngoan.NV"
"695","THCS_DocBinhKieu","7","7A1","3","Chieu","1","Tiếng Anh","Nguyễn Thị Mai Khanh","Khanh.NTM"
"696","THCS_DocBinhKieu","7","7A1","3","Chieu","2","Tiếng Anh","Nguyễn Thị Mai Khanh","Khanh.NTM"
"697","THCS_DocBinhKieu","7","7A1","3","Chieu","3","Tin học","Mai Phước Lộc","Lộc.MP"
"698","THCS_DocBinhKieu","7","7A1","3","Chieu","4","Ngữ văn","Lê Thị Hoài An","An.LTH"
"699","THCS_DocBinhKieu","7","7A1","3","Chieu","5","Ngữ văn","Lê Thị Hoài An","An.LTH"
"700","THCS_DocBinhKieu","7","7A1","4","Chieu","1","Khoa học tự nhiên","Nguyễn Thị Hiếu","Hiếu.NT"
"701","THCS_DocBinhKieu","7","7A1","4","Chieu","2","Khoa học tự nhiên","Nguyễn Thị Hiếu","Hiếu.NT"
"702","THCS_DocBinhKieu","7","7A1","4","Chieu","3","Tiếng Anh","Nguyễn Thị Mai Khanh","Khanh.NTM"
"703","THCS_DocBinhKieu","7","7A1","4","Chieu","4","Giáo dục thể chất","Lê Văn Nguyên","Nguyên.LV"
"704","THCS_DocBinhKieu","7","7A1","4","Chieu","5","Giáo dục thể chất","Lê Văn Nguyên","Nguyên.LV"
"705","THCS_DocBinhKieu","7","7A1","5","Chieu","1","Lịch sử","Lê Thị Kim The","The.LTK"
"706","THCS_DocBinhKieu","7","7A1","5","Chieu","2","Âm nhạc","Lê Thị Tuyết Xanh","Xanh.LTT"
"707","THCS_DocBinhKieu","7","7A1","6","Chieu","1","Mỹ thuật","Lê Minh Đạt","Đạt.LM"
"708","THCS_DocBinhKieu","7","7A1","6","Chieu","2","Công nghệ","Trần Thị Cẩm","Cẩm.TT"
"709","THCS_DocBinhKieu","7","7A1","6","Chieu","3","Toán học","Nguyễn Văn Ngoan","Ngoan.NV"
"710","THCS_DocBinhKieu","7","7A1","6","Chieu","4","Toán học","Nguyễn Văn Ngoan","Ngoan.NV"
"711","THCS_DocBinhKieu","7","7A1","6","Chieu","5","Lịch sử","Lê Thị Kim The","The.LTK"
"712","THCS_DocBinhKieu","7","7A1","7","Chieu","1","Ngữ văn","Lê Thị Hoài An","An.LTH"
"713","THCS_DocBinhKieu","7","7A1","7","Chieu","2","Ngữ văn","Lê Thị Hoài An","An.LTH"
"714","THCS_DocBinhKieu","7","7A1","7","Chieu","3","Khoa học tự nhiên","Nguyễn Thị Hiếu","Hiếu.NT"
"715","THCS_DocBinhKieu","7","7A1","7","Chieu","4","Toán học","Nguyễn Văn Ngoan","Ngoan.NV"
"716","THCS_DocBinhKieu","7","7A1","7","Chieu","5","Sinh hoạt lớp","Nguyễn Văn Ngoan","Ngoan.NV"
"717","THCS_DocBinhKieu","7","7A2","2","Chieu","1","Địa lí","Nguyễn Thị Kim Đỉnh","Đỉnh.NTK"
"718","THCS_DocBinhKieu","7","7A2","2","Chieu","2","Toán học","Nguyễn Văn Tới","Tới.NV"
"719","THCS_DocBinhKieu","7","7A2","2","Chieu","3","Toán học","Nguyễn Văn Tới","Tới.NV"
"720","THCS_DocBinhKieu","7","7A2","2","Chieu","4","Khoa học tự nhiên","Nguyễn Thị Hiếu","Hiếu.NT"
"721","THCS_DocBinhKieu","7","7A2","2","Chieu","5","Chào cờ","Mai Phước Lộc","Lộc.MP"
"722","THCS_DocBinhKieu","7","7A2","3","Chieu","1","Ngữ văn","Hứa Thùy Dương","Dương.HT"
"723","THCS_DocBinhKieu","7","7A2","3","Sang","1","HĐTNHN (Chuyên đề)","Trần Thị Cẩm","Cẩm.TT"
"724","THCS_DocBinhKieu","7","7A2","3","Chieu","2","Giáo dục công dân","Lê Hồng Thúy","Thúy.LH"
"725","THCS_DocBinhKieu","7","7A2","3","Sang","2","HĐTNHN (Quy mô lớp)","Mai Phước Lộc","Lộc.MP"
"726","THCS_DocBinhKieu","7","7A2","3","Chieu","3","Lịch sử","Lê Thị Kim The","The.LTK"
"727","THCS_DocBinhKieu","7","7A2","3","Chieu","4","Tiếng Anh","Nguyễn Thị Thùy Dương","Dương.NTT"
"728","THCS_DocBinhKieu","7","7A2","3","Chieu","5","Tiếng Anh","Nguyễn Thị Thùy Dương","Dương.NTT"
"729","THCS_DocBinhKieu","7","7A2","4","Chieu","1","Ngữ văn","Hứa Thùy Dương","Dương.HT"
"730","THCS_DocBinhKieu","7","7A2","4","Chieu","2","Ngữ văn","Hứa Thùy Dương","Dương.HT"
"731","THCS_DocBinhKieu","7","7A2","4","Chieu","3","Khoa học tự nhiên","Nguyễn Thị Hiếu","Hiếu.NT"
"732","THCS_DocBinhKieu","7","7A2","4","Chieu","4","Âm nhạc","Lê Thị Tuyết Xanh","Xanh.LTT"
"733","THCS_DocBinhKieu","7","7A2","4","Chieu","5","Lịch sử","Lê Thị Kim The","The.LTK"
"734","THCS_DocBinhKieu","7","7A2","5","Chieu","1","Ngữ văn","Hứa Thùy Dương","Dương.HT"
"735","THCS_DocBinhKieu","7","7A2","5","Chieu","2","Tiếng Anh","Nguyễn Thị Thùy Dương","Dương.NTT"
"736","THCS_DocBinhKieu","7","7A2","6","Chieu","1","Công nghệ","Trần Thị Cẩm","Cẩm.TT"
"737","THCS_DocBinhKieu","7","7A2","6","Chieu","2","Giáo dục thể chất","Lê Văn Nguyên","Nguyên.LV"
"738","THCS_DocBinhKieu","7","7A2","6","Chieu","3","Giáo dục thể chất","Lê Văn Nguyên","Nguyên.LV"
"739","THCS_DocBinhKieu","7","7A2","6","Chieu","4","Toán học","Nguyễn Văn Tới","Tới.NV"
"740","THCS_DocBinhKieu","7","7A2","6","Chieu","5","Toán học","Nguyễn Văn Tới","Tới.NV"
"741","THCS_DocBinhKieu","7","7A2","7","Chieu","1","Khoa học tự nhiên","Nguyễn Thị Hiếu","Hiếu.NT"
"742","THCS_DocBinhKieu","7","7A2","7","Chieu","2","Khoa học tự nhiên","Nguyễn Thị Hiếu","Hiếu.NT"
"743","THCS_DocBinhKieu","7","7A2","7","Chieu","3","Mỹ thuật","Lê Minh Đạt","Đạt.LM"
"744","THCS_DocBinhKieu","7","7A2","7","Chieu","4","Tin học","Mai Phước Lộc","Lộc.MP"
"745","THCS_DocBinhKieu","7","7A2","7","Chieu","5","Sinh hoạt lớp","Mai Phước Lộc","Lộc.MP"
"746","THCS_DocBinhKieu","7","7A3","2","Chieu","1","Ngữ văn","Hứa Thùy Dương","Dương.HT"
"747","THCS_DocBinhKieu","7","7A3","2","Sang","1","HĐTNHN (Quy mô lớp)","Nguyễn Quốc Nguyễn","Nguyễn.NQ"
"748","THCS_DocBinhKieu","7","7A3","2","Chieu","2","Ngữ văn","Hứa Thùy Dương","Dương.HT"
"749","THCS_DocBinhKieu","7","7A3","2","Sang","2","HĐTNHN (Chuyên đề)","Trần Thị Cẩm","Cẩm.TT"
"750","THCS_DocBinhKieu","7","7A3","2","Chieu","3","Khoa học tự nhiên","Nguyễn Thị Cẩm Nhung","Nhung.NTC"
"751","THCS_DocBinhKieu","7","7A3","2","Chieu","4","Toán học","Nguyễn Quốc Nguyễn","Nguyễn.NQ"
"752","THCS_DocBinhKieu","7","7A3","2","Chieu","5","Chào cờ","Nguyễn Quốc Nguyễn","Nguyễn.NQ"
"753","THCS_DocBinhKieu","7","7A3","3","Chieu","1","Tin học","Mai Phước Lộc","Lộc.MP"
"754","THCS_DocBinhKieu","7","7A3","3","Chieu","2","Ngữ văn","Hứa Thùy Dương","Dương.HT"
"755","THCS_DocBinhKieu","7","7A3","3","Chieu","3","Giáo dục công dân","Lê Hồng Thúy","Thúy.LH"
"756","THCS_DocBinhKieu","7","7A3","3","Chieu","4","Lịch sử","Lê Thị Kim The","The.LTK"
"757","THCS_DocBinhKieu","7","7A3","3","Chieu","5","Mỹ thuật","Lê Minh Đạt","Đạt.LM"
"758","THCS_DocBinhKieu","7","7A3","4","Chieu","1","Khoa học tự nhiên","Nguyễn Thị Cẩm Nhung","Nhung.NTC"
"759","THCS_DocBinhKieu","7","7A3","4","Chieu","2","Toán học","Nguyễn Quốc Nguyễn","Nguyễn.NQ"
"760","THCS_DocBinhKieu","7","7A3","4","Chieu","3","Toán học","Nguyễn Quốc Nguyễn","Nguyễn.NQ"
"761","THCS_DocBinhKieu","7","7A3","4","Chieu","4","Tiếng Anh","Nguyễn Thị Mai Khanh","Khanh.NTM"
"762","THCS_DocBinhKieu","7","7A3","4","Chieu","5","Âm nhạc","Lê Thị Tuyết Xanh","Xanh.LTT"
"763","THCS_DocBinhKieu","7","7A3","5","Chieu","1","Địa lí","Nguyễn Thị Kim Đỉnh","Đỉnh.NTK"
"764","THCS_DocBinhKieu","7","7A3","5","Chieu","2","Lịch sử","Lê Thị Kim The","The.LTK"
"765","THCS_DocBinhKieu","7","7A3","6","Chieu","1","Ngữ văn","Hứa Thùy Dương","Dương.HT"
"766","THCS_DocBinhKieu","7","7A3","6","Chieu","2","Tiếng Anh","Nguyễn Thị Mai Khanh","Khanh.NTM"
"767","THCS_DocBinhKieu","7","7A3","6","Chieu","3","Tiếng Anh","Nguyễn Thị Mai Khanh","Khanh.NTM"
"768","THCS_DocBinhKieu","7","7A3","6","Chieu","4","Giáo dục thể chất","Lê Văn Nguyên","Nguyên.LV"
"769","THCS_DocBinhKieu","7","7A3","6","Chieu","5","Giáo dục thể chất","Lê Văn Nguyên","Nguyên.LV"
"770","THCS_DocBinhKieu","7","7A3","7","Chieu","1","Công nghệ","Trần Thị Cẩm","Cẩm.TT"
"771","THCS_DocBinhKieu","7","7A3","7","Chieu","2","Khoa học tự nhiên","Nguyễn Thị Cẩm Nhung","Nhung.NTC"
"772","THCS_DocBinhKieu","7","7A3","7","Chieu","3","Khoa học tự nhiên","Nguyễn Thị Cẩm Nhung","Nhung.NTC"
"773","THCS_DocBinhKieu","7","7A3","7","Chieu","4","Toán học","Nguyễn Quốc Nguyễn","Nguyễn.NQ"
"774","THCS_DocBinhKieu","7","7A3","7","Chieu","5","Sinh hoạt lớp","Nguyễn Quốc Nguyễn","Nguyễn.NQ"
"775","THCS_DocBinhKieu","7","7A4","2","Chieu","1","Khoa học tự nhiên","Nguyễn Thị Cẩm Nhung","Nhung.NTC"
"776","THCS_DocBinhKieu","7","7A4","2","Chieu","2","Khoa học tự nhiên","Nguyễn Thị Cẩm Nhung","Nhung.NTC"
"777","THCS_DocBinhKieu","7","7A4","2","Chieu","3","Âm nhạc","Lê Thị Tuyết Xanh","Xanh.LTT"
"778","THCS_DocBinhKieu","7","7A4","2","Chieu","4","Tin học","Mai Phước Lộc","Lộc.MP"
"779","THCS_DocBinhKieu","7","7A4","2","Chieu","5","Chào cờ","Lê Ngọc Ẩn","Ẩn.LN"
"780","THCS_DocBinhKieu","7","7A4","3","Chieu","1","Ngữ văn","Nguyễn Thị Kim Xoa","Xoa.NTK"
"781","THCS_DocBinhKieu","7","7A4","3","Sang","1","HĐTNHN (Quy mô lớp)","Lê Ngọc Ẩn","Ẩn.LN"
"782","THCS_DocBinhKieu","7","7A4","3","Chieu","2","Ngữ văn","Nguyễn Thị Kim Xoa","Xoa.NTK"
"783","THCS_DocBinhKieu","7","7A4","3","Sang","2","HĐTNHN (Chuyên đề)","Trần Thị Cẩm","Cẩm.TT"
"784","THCS_DocBinhKieu","7","7A4","3","Chieu","3","Mỹ thuật","Lê Minh Đạt","Đạt.LM"
"785","THCS_DocBinhKieu","7","7A4","3","Chieu","4","Toán học","Lê Văn Toàn","Toàn.LV"
"786","THCS_DocBinhKieu","7","7A4","3","Chieu","5","Toán học","Lê Văn Toàn","Toàn.LV"
"787","THCS_DocBinhKieu","7","7A4","4","Chieu","1","Giáo dục công dân","Lê Hồng Thúy","Thúy.LH"
"788","THCS_DocBinhKieu","7","7A4","4","Chieu","2","Khoa học tự nhiên","Nguyễn Thị Cẩm Nhung","Nhung.NTC"
"789","THCS_DocBinhKieu","7","7A4","4","Chieu","3","Khoa học tự nhiên","Nguyễn Thị Cẩm Nhung","Nhung.NTC"
"790","THCS_DocBinhKieu","7","7A4","4","Chieu","4","Lịch sử","Lê Thị Kim The","The.LTK"
"791","THCS_DocBinhKieu","7","7A4","4","Chieu","5","Ngữ văn","Nguyễn Thị Kim Xoa","Xoa.NTK"
"792","THCS_DocBinhKieu","7","7A4","5","Chieu","1","Tiếng Anh","Nguyễn Thị Thùy Dương","Dương.NTT"
"793","THCS_DocBinhKieu","7","7A4","5","Chieu","2","Địa lí","Nguyễn Thị Kim Đỉnh","Đỉnh.NTK"
"794","THCS_DocBinhKieu","7","7A4","6","Chieu","1","Tiếng Anh","Nguyễn Thị Thùy Dương","Dương.NTT"
"795","THCS_DocBinhKieu","7","7A4","6","Chieu","2","Tiếng Anh","Nguyễn Thị Thùy Dương","Dương.NTT"
"796","THCS_DocBinhKieu","7","7A4","6","Chieu","3","Lịch sử","Lê Thị Kim The","The.LTK"
"797","THCS_DocBinhKieu","7","7A4","6","Chieu","4","Toán học","Lê Văn Toàn","Toàn.LV"
"798","THCS_DocBinhKieu","7","7A4","6","Chieu","5","Toán học","Lê Văn Toàn","Toàn.LV"
"799","THCS_DocBinhKieu","7","7A4","7","Chieu","1","Ngữ văn","Nguyễn Thị Kim Xoa","Xoa.NTK"
"800","THCS_DocBinhKieu","7","7A4","7","Chieu","2","Giáo dục thể chất","Lê Ngọc Ẩn","Ẩn.LN"
"801","THCS_DocBinhKieu","7","7A4","7","Chieu","3","Giáo dục thể chất","Lê Ngọc Ẩn","Ẩn.LN"
"802","THCS_DocBinhKieu","7","7A4","7","Chieu","4","Công nghệ","Trần Thị Cẩm","Cẩm.TT"
"803","THCS_DocBinhKieu","7","7A4","7","Chieu","5","Sinh hoạt lớp","Lê Ngọc Ẩn","Ẩn.LN"
"804","THCS_DocBinhKieu","7","7A5","2","Chieu","1","Khoa học tự nhiên","Nguyễn Thị Hiếu","Hiếu.NT"
"805","THCS_DocBinhKieu","7","7A5","2","Sang","1","HĐTNHN (Chuyên đề)","Trần Thị Cẩm","Cẩm.TT"
"806","THCS_DocBinhKieu","7","7A5","2","Chieu","2","Toán học","Lê Cao Toàn","Toàn.LC"
"807","THCS_DocBinhKieu","7","7A5","2","Sang","2","HĐTNHN (Quy mô lớp)","Lê Thái Phương","Phương.LT"
"808","THCS_DocBinhKieu","7","7A5","2","Chieu","3","Toán học","Lê Cao Toàn","Toàn.LC"
"809","THCS_DocBinhKieu","7","7A5","2","Chieu","4","Công nghệ","Trần Thị Cẩm","Cẩm.TT"
"810","THCS_DocBinhKieu","7","7A5","2","Chieu","5","Chào cờ","Nguyễn Thị Hiếu","Hiếu.NT"
"811","THCS_DocBinhKieu","7","7A5","3","Chieu","1","Âm nhạc","Lê Thị Tuyết Xanh","Xanh.LTT"
"812","THCS_DocBinhKieu","7","7A5","3","Chieu","2","Giáo dục công dân","Nguyễn Thị Xe","Xe.NT"
"813","THCS_DocBinhKieu","7","7A5","3","Chieu","3","Tiếng Anh","Nguyễn Thị Mai Khanh","Khanh.NTM"
"814","THCS_DocBinhKieu","7","7A5","3","Chieu","4","Giáo dục thể chất","Lê Văn Nguyên","Nguyên.LV"
"815","THCS_DocBinhKieu","7","7A5","3","Chieu","5","Giáo dục thể chất","Lê Văn Nguyên","Nguyên.LV"
"816","THCS_DocBinhKieu","7","7A5","4","Chieu","1","Tiếng Anh","Nguyễn Thị Mai Khanh","Khanh.NTM"
"817","THCS_DocBinhKieu","7","7A5","4","Chieu","2","Tiếng Anh","Nguyễn Thị Mai Khanh","Khanh.NTM"
"818","THCS_DocBinhKieu","7","7A5","4","Chieu","3","Ngữ văn","Nguyễn Thị Kim Xoa","Xoa.NTK"
"819","THCS_DocBinhKieu","7","7A5","4","Chieu","4","Toán học","Lê Cao Toàn","Toàn.LC"
"820","THCS_DocBinhKieu","7","7A5","4","Chieu","5","Toán học","Lê Cao Toàn","Toàn.LC"
"821","THCS_DocBinhKieu","7","7A5","5","Chieu","1","Khoa học tự nhiên","Nguyễn Thị Hiếu","Hiếu.NT"
"822","THCS_DocBinhKieu","7","7A5","5","Chieu","2","Khoa học tự nhiên","Nguyễn Thị Hiếu","Hiếu.NT"
"823","THCS_DocBinhKieu","7","7A5","6","Chieu","1","Ngữ văn","Nguyễn Thị Kim Xoa","Xoa.NTK"
"824","THCS_DocBinhKieu","7","7A5","6","Chieu","2","Ngữ văn","Nguyễn Thị Kim Xoa","Xoa.NTK"
"825","THCS_DocBinhKieu","7","7A5","6","Chieu","3","Mỹ thuật","Lê Minh Đạt","Đạt.LM"
"826","THCS_DocBinhKieu","7","7A5","6","Chieu","4","Lịch sử","Lê Thị Kim The","The.LTK"
"827","THCS_DocBinhKieu","7","7A5","6","Chieu","5","Địa lí","Ngô Anh Tuấn","Tuấn.NA"
"828","THCS_DocBinhKieu","7","7A5","7","Chieu","1","Lịch sử","Lê Thị Kim The","The.LTK"
"829","THCS_DocBinhKieu","7","7A5","7","Chieu","2","Ngữ văn","Nguyễn Thị Kim Xoa","Xoa.NTK"
"830","THCS_DocBinhKieu","7","7A5","7","Chieu","3","Tin học","Mai Phước Lộc","Lộc.MP"
"831","THCS_DocBinhKieu","7","7A5","7","Chieu","4","Khoa học tự nhiên","Nguyễn Thị Hiếu","Hiếu.NT"
"832","THCS_DocBinhKieu","7","7A5","7","Chieu","5","Sinh hoạt lớp","Nguyễn Thị Hiếu","Hiếu.NT"
"833","THCS_DocBinhKieu","7","7A6","2","Chieu","1","Khoa học tự nhiên","Võ Hoàng Toàn","Toàn.VH"
"834","THCS_DocBinhKieu","7","7A6","2","Chieu","2","Khoa học tự nhiên","Võ Hoàng Toàn","Toàn.VH"
"835","THCS_DocBinhKieu","7","7A6","2","Chieu","3","Tiếng Anh","Nguyễn Thị Thùy Dương","Dương.NTT"
"836","THCS_DocBinhKieu","7","7A6","2","Chieu","4","Tiếng Anh","Nguyễn Thị Thùy Dương","Dương.NTT"
"837","THCS_DocBinhKieu","7","7A6","2","Chieu","5","Chào cờ","Trần Thị Cẩm","Cẩm.TT"
"838","THCS_DocBinhKieu","7","7A6","3","Chieu","1","Giáo dục công dân","Nguyễn Thị Xe","Xe.NT"
"839","THCS_DocBinhKieu","7","7A6","3","Chieu","2","Âm nhạc","Lê Thị Tuyết Xanh","Xanh.LTT"
"840","THCS_DocBinhKieu","7","7A6","3","Chieu","3","Tiếng Anh","Nguyễn Thị Thùy Dương","Dương.NTT"
"841","THCS_DocBinhKieu","7","7A6","3","Chieu","4","Toán học","Trần Văn Giang","Giang.TV"
"842","THCS_DocBinhKieu","7","7A6","3","Chieu","5","Toán học","Trần Văn Giang","Giang.TV"
"843","THCS_DocBinhKieu","7","7A6","4","Chieu","1","Ngữ văn","Lê Thị Hoài An","An.LTH"
"844","THCS_DocBinhKieu","7","7A6","4","Chieu","2","Ngữ văn","Lê Thị Hoài An","An.LTH"
"845","THCS_DocBinhKieu","7","7A6","4","Chieu","3","Lịch sử","Lê Thị Kim The","The.LTK"
"846","THCS_DocBinhKieu","7","7A6","4","Chieu","4","Giáo dục thể chất","Nguyễn Thanh Hùng","Hùng.NThanh"
"847","THCS_DocBinhKieu","7","7A6","4","Chieu","5","Giáo dục thể chất","Nguyễn Thanh Hùng","Hùng.NThanh"
"848","THCS_DocBinhKieu","7","7A6","5","Chieu","1","Ngữ văn","Lê Thị Hoài An","An.LTH"
"849","THCS_DocBinhKieu","7","7A6","5","Chieu","2","Ngữ văn","Lê Thị Hoài An","An.LTH"
"850","THCS_DocBinhKieu","7","7A6","6","Chieu","1","Khoa học tự nhiên","Võ Hoàng Toàn","Toàn.VH"
"851","THCS_DocBinhKieu","7","7A6","6","Sang","1","HĐTNHN (Quy mô lớp)","Trần Thị Cẩm","Cẩm.TT"
"852","THCS_DocBinhKieu","7","7A6","6","Chieu","2","Khoa học tự nhiên","Võ Hoàng Toàn","Toàn.VH"
"853","THCS_DocBinhKieu","7","7A6","6","Sang","2","HĐTNHN (Chuyên đề)","Trần Thị Cẩm","Cẩm.TT"
"854","THCS_DocBinhKieu","7","7A6","6","Chieu","3","Địa lí","Ngô Anh Tuấn","Tuấn.NA"
"855","THCS_DocBinhKieu","7","7A6","6","Chieu","4","Toán học","Trần Văn Giang","Giang.TV"
"856","THCS_DocBinhKieu","7","7A6","6","Chieu","5","Toán học","Trần Văn Giang","Giang.TV"
"857","THCS_DocBinhKieu","7","7A6","7","Chieu","1","Tin học","Mai Phước Lộc","Lộc.MP"
"858","THCS_DocBinhKieu","7","7A6","7","Chieu","2","Lịch sử","Lê Thị Kim The","The.LTK"
"859","THCS_DocBinhKieu","7","7A6","7","Chieu","3","Công nghệ","Trần Thị Cẩm","Cẩm.TT"
"860","THCS_DocBinhKieu","7","7A6","7","Chieu","4","Mỹ thuật","Lê Minh Đạt","Đạt.LM"
"861","THCS_DocBinhKieu","7","7A6","7","Chieu","5","Sinh hoạt lớp","Trần Thị Cẩm","Cẩm.TT"
"862","THCS_TanKieu","7","7A7","2","Chieu","1","Ngữ văn","Nguyễn Hiền Vi","Vi.NH"
"863","THCS_TanKieu","7","7A7","2","Sang","1","HĐTNHN (Chuyên đề)","Trần Kim Phương","Phương.TK"
"864","THCS_TanKieu","7","7A7","2","Chieu","2","Ngữ văn","Nguyễn Hiền Vi","Vi.NH"
"865","THCS_TanKieu","7","7A7","2","Sang","2","HĐTNHN (Quy mô lớp)","Trần Kim Phương","Phương.TK"
"866","THCS_TanKieu","7","7A7","2","Chieu","3","Lịch sử và Địa lí","Phạm Thị Mỹ Châu","Châu.PTM"
"867","THCS_TanKieu","7","7A7","2","Chieu","4","Lịch sử và Địa lí","Phạm Thị Mỹ Châu","Châu.PTM"
"868","THCS_TanKieu","7","7A7","2","Chieu","5","Chào cờ","Trần Kim Phương","Phương.TK"
"869","THCS_TanKieu","7","7A7","3","Chieu","1","Lịch sử và Địa lí","Phạm Thị Mỹ Châu","Châu.PTM"
"870","THCS_TanKieu","7","7A7","3","Chieu","2","Ngữ văn","Nguyễn Hiền Vi","Vi.NH"
"871","THCS_TanKieu","7","7A7","3","Chieu","3","Toán học","Huỳnh Thị Huỳnh Nga","Nga.HTH"
"872","THCS_TanKieu","7","7A7","3","Chieu","4","Khoa học tự nhiên","Trần Kim Phương","Phương.TK"
"873","THCS_TanKieu","7","7A7","3","Chieu","5","Khoa học tự nhiên","Trần Kim Phương","Phương.TK"
"874","THCS_TanKieu","7","7A7","4","Chieu","1","Toán học","Huỳnh Thị Huỳnh Nga","Nga.HTH"
"875","THCS_TanKieu","7","7A7","4","Chieu","2","Toán học","Huỳnh Thị Huỳnh Nga","Nga.HTH"
"876","THCS_TanKieu","7","7A7","4","Chieu","3","Tin học","Lê Phước Hậu","Hậu.LP"
"877","THCS_TanKieu","7","7A7","4","Chieu","4","Giáo dục công dân","Nguyễn Mỹ Ngân","Ngân.NM"
"878","THCS_TanKieu","7","7A7","4","Chieu","5","Tiếng Anh","Trương Sơn Bền","Bền.TS"
"879","THCS_TanKieu","7","7A7","5","Chieu","1","Tiếng Anh","Trương Sơn Bền","Bền.TS"
"880","THCS_TanKieu","7","7A7","5","Chieu","2","Tiếng Anh","Trương Sơn Bền","Bền.TS"
"881","THCS_TanKieu","7","7A7","6","Chieu","1","Toán học","Huỳnh Thị Huỳnh Nga","Nga.HTH"
"882","THCS_TanKieu","7","7A7","6","Chieu","2","Công nghệ","Phan Văn Tặt","Tặt.PV"
"883","THCS_TanKieu","7","7A7","6","Chieu","3","Ngữ văn","Nguyễn Hiền Vi","Vi.NH"
"884","THCS_TanKieu","7","7A7","6","Chieu","4","Khoa học tự nhiên","Trần Kim Phương","Phương.TK"
"885","THCS_TanKieu","7","7A7","6","Chieu","5","Khoa học tự nhiên","Trần Kim Phương","Phương.TK"
"886","THCS_TanKieu","7","7A7","7","Chieu","1","Âm nhạc","Nguyễn Anh Văn","Văn.NA"
"887","THCS_TanKieu","7","7A7","7","Chieu","2","Mỹ thuật","Trần Thị Mỹ Quốc","Quốc.TTM"
"888","THCS_TanKieu","7","7A7","7","Chieu","3","Giáo dục thể chất","Lê Văn Chính","Chính.LV"
"889","THCS_TanKieu","7","7A7","7","Chieu","4","Giáo dục thể chất","Lê Văn Chính","Chính.LV"
"890","THCS_TanKieu","7","7A7","7","Chieu","5","Sinh hoạt lớp","Trần Kim Phương","Phương.TK"
"891","THCS_TanKieu","7","7A8","2","Chieu","1","Lịch sử và Địa lí","Phạm Thị Mỹ Châu","Châu.PTM"
"892","THCS_TanKieu","7","7A8","2","Chieu","2","Lịch sử và Địa lí","Phạm Thị Mỹ Châu","Châu.PTM"
"893","THCS_TanKieu","7","7A8","2","Chieu","3","Khoa học tự nhiên","Trần Kim Phương","Phương.TK"
"894","THCS_TanKieu","7","7A8","2","Chieu","4","Khoa học tự nhiên","Trần Kim Phương","Phương.TK"
"895","THCS_TanKieu","7","7A8","2","Chieu","5","Chào cờ","Phạm Thị Mỹ Châu","Châu.PTM"
"896","THCS_TanKieu","7","7A8","3","Chieu","1","Tin học","Lê Phước Hậu","Hậu.LP"
"897","THCS_TanKieu","7","7A8","3","Chieu","2","Giáo dục công dân","Nguyễn Mỹ Ngân","Ngân.NM"
"898","THCS_TanKieu","7","7A8","3","Chieu","3","Lịch sử và Địa lí","Phạm Thị Mỹ Châu","Châu.PTM"
"899","THCS_TanKieu","7","7A8","3","Chieu","4","Toán học","Huỳnh Thị Huỳnh Nga","Nga.HTH"
"900","THCS_TanKieu","7","7A8","3","Chieu","5","Toán học","Huỳnh Thị Huỳnh Nga","Nga.HTH"
"901","THCS_TanKieu","7","7A8","4","Chieu","1","Khoa học tự nhiên","Trần Kim Phương","Phương.TK"
"902","THCS_TanKieu","7","7A8","4","Chieu","2","Khoa học tự nhiên","Trần Kim Phương","Phương.TK"
"903","THCS_TanKieu","7","7A8","4","Chieu","3","Tiếng Anh","Trương Sơn Bền","Bền.TS"
"904","THCS_TanKieu","7","7A8","4","Chieu","4","Toán học","Huỳnh Thị Huỳnh Nga","Nga.HTH"
"905","THCS_TanKieu","7","7A8","4","Chieu","5","Toán học","Huỳnh Thị Huỳnh Nga","Nga.HTH"
"906","THCS_TanKieu","7","7A8","5","Chieu","1","Âm nhạc","Nguyễn Anh Văn","Văn.NA"
"907","THCS_TanKieu","7","7A8","5","Sang","1","HĐTNHN (Chuyên đề)","Phan Văn Tặt","Tặt.PV"
"908","THCS_TanKieu","7","7A8","5","Chieu","2","Mỹ thuật","Trần Thị Mỹ Quốc","Quốc.TTM"
"909","THCS_TanKieu","7","7A8","5","Sang","2","HĐTNHN (Quy mô lớp)","Phan Văn Tặt","Tặt.PV"
"910","THCS_TanKieu","7","7A8","6","Chieu","1","Tiếng Anh","Trương Sơn Bền","Bền.TS"
"911","THCS_TanKieu","7","7A8","6","Chieu","2","Tiếng Anh","Trương Sơn Bền","Bền.TS"
"912","THCS_TanKieu","7","7A8","6","Chieu","3","Công nghệ","Phan Văn Tặt","Tặt.PV"
"913","THCS_TanKieu","7","7A8","6","Chieu","4","Ngữ văn","Nguyễn Hiền Vi","Vi.NH"
"914","THCS_TanKieu","7","7A8","6","Chieu","5","Ngữ văn","Nguyễn Hiền Vi","Vi.NH"
"915","THCS_TanKieu","7","7A8","7","Chieu","1","Giáo dục thể chất","Lê Văn Chính","Chính.LV"
"916","THCS_TanKieu","7","7A8","7","Chieu","2","Giáo dục thể chất","Lê Văn Chính","Chính.LV"
"917","THCS_TanKieu","7","7A8","7","Chieu","3","Ngữ văn","Nguyễn Hiền Vi","Vi.NH"
"918","THCS_TanKieu","7","7A8","7","Chieu","4","Ngữ văn","Nguyễn Hiền Vi","Vi.NH"
"919","THCS_TanKieu","7","7A8","7","Chieu","5","Sinh hoạt lớp","Phạm Thị Mỹ Châu","Châu.PTM"
"920","THCS_TanKieu","7","7A9","2","Chieu","1","Giáo dục công dân","Nguyễn Mỹ Ngân","Ngân.NM"
"921","THCS_TanKieu","7","7A9","2","Sang","1","HĐTNHN (Quy mô lớp)","Phan Văn Tặt","Tặt.PV"
"922","THCS_TanKieu","7","7A9","2","Chieu","2","Tin học","Lê Phước Hậu","Hậu.LP"
"923","THCS_TanKieu","7","7A9","2","Sang","2","HĐTNHN (Chuyên đề)","Phan Văn Tặt","Tặt.PV"
"924","THCS_TanKieu","7","7A9","2","Chieu","3","Giáo dục thể chất","Lê Văn Chính","Chính.LV"
"925","THCS_TanKieu","7","7A9","2","Chieu","4","Giáo dục thể chất","Lê Văn Chính","Chính.LV"
"926","THCS_TanKieu","7","7A9","2","Chieu","5","Chào cờ","Lê Văn Chính","Chính.LV"
"927","THCS_TanKieu","7","7A9","3","Chieu","1","Toán học","Huỳnh Thị Huỳnh Nga","Nga.HTH"
"928","THCS_TanKieu","7","7A9","3","Chieu","2","Toán học","Huỳnh Thị Huỳnh Nga","Nga.HTH"
"929","THCS_TanKieu","7","7A9","3","Chieu","3","Khoa học tự nhiên","Trần Kim Phương","Phương.TK"
"930","THCS_TanKieu","7","7A9","3","Chieu","4","Ngữ văn","Nguyễn Hiền Vi","Vi.NH"
"931","THCS_TanKieu","7","7A9","3","Chieu","5","Ngữ văn","Nguyễn Hiền Vi","Vi.NH"
"932","THCS_TanKieu","7","7A9","4","Chieu","1","Tiếng Anh","Trương Sơn Bền","Bền.TS"
"933","THCS_TanKieu","7","7A9","4","Chieu","2","Tiếng Anh","Trương Sơn Bền","Bền.TS"
"934","THCS_TanKieu","7","7A9","4","Chieu","3","Mỹ thuật","Trần Thị Mỹ Quốc","Quốc.TTM"
"935","THCS_TanKieu","7","7A9","4","Chieu","4","Khoa học tự nhiên","Trần Kim Phương","Phương.TK"
"936","THCS_TanKieu","7","7A9","4","Chieu","5","Khoa học tự nhiên","Trần Kim Phương","Phương.TK"
"937","THCS_TanKieu","7","7A9","5","Chieu","1","Lịch sử và Địa lí","Phạm Thị Mỹ Châu","Châu.PTM"
"938","THCS_TanKieu","7","7A9","5","Chieu","2","Lịch sử và Địa lí","Phạm Thị Mỹ Châu","Châu.PTM"
"939","THCS_TanKieu","7","7A9","6","Chieu","1","Ngữ văn","Nguyễn Hiền Vi","Vi.NH"
"940","THCS_TanKieu","7","7A9","6","Chieu","2","Toán học","Huỳnh Thị Huỳnh Nga","Nga.HTH"
"941","THCS_TanKieu","7","7A9","6","Chieu","3","Toán học","Huỳnh Thị Huỳnh Nga","Nga.HTH"
"942","THCS_TanKieu","7","7A9","6","Chieu","4","Tiếng Anh","Trương Sơn Bền","Bền.TS"
"943","THCS_TanKieu","7","7A9","6","Chieu","5","Công nghệ","Phan Văn Tặt","Tặt.PV"
"944","THCS_TanKieu","7","7A9","7","Chieu","1","Ngữ văn","Nguyễn Hiền Vi","Vi.NH"
"945","THCS_TanKieu","7","7A9","7","Chieu","2","Âm nhạc","Nguyễn Anh Văn","Văn.NA"
"946","THCS_TanKieu","7","7A9","7","Chieu","3","Khoa học tự nhiên","Trần Kim Phương","Phương.TK"
"947","THCS_TanKieu","7","7A9","7","Chieu","4","Lịch sử và Địa lí","Phạm Thị Mỹ Châu","Châu.PTM"
"948","THCS_TanKieu","7","7A9","7","Chieu","5","Sinh hoạt lớp","Lê Văn Chính","Chính.LV"
"949","THCS_DocBinhKieu","8","8A1","2","Sang","1","Chào cờ","Nguyễn Thái Hùng","Hùng.NThái"
"950","THCS_DocBinhKieu","8","8A1","2","Sang","2","Toán học","Nguyễn Thái Hùng","Hùng.NThái"
"951","THCS_DocBinhKieu","8","8A1","2","Sang","3","Công nghệ","Trần Phi Hải","Hải.TP"
"952","THCS_DocBinhKieu","8","8A1","2","Sang","4","Giáo dục công dân","Nguyễn Thị Xe","Xe.NT"
"953","THCS_DocBinhKieu","8","8A1","2","Sang","5","HĐTNHN (Chuyên đề)","Trần Thị Hậu","Hậu.TTH"
"954","THCS_DocBinhKieu","8","8A1","3","Sang","1","Ngữ văn","Lê Thị Hoài An","An.LTH"
"955","THCS_DocBinhKieu","8","8A1","3","Sang","2","Ngữ văn","Lê Thị Hoài An","An.LTH"
"956","THCS_DocBinhKieu","8","8A1","3","Sang","3","Tiếng Anh","Trần Thanh Hậu","Hậu.TT"
"957","THCS_DocBinhKieu","8","8A1","3","Sang","4","Tiếng Anh","Trần Thanh Hậu","Hậu.TT"
"958","THCS_DocBinhKieu","8","8A1","3","Sang","5","Lịch sử","Lê Thị Kim The","The.LTK"
"959","THCS_DocBinhKieu","8","8A1","4","Sang","1","Ngữ văn","Lê Thị Hoài An","An.LTH"
"960","THCS_DocBinhKieu","8","8A1","4","Sang","2","Công nghệ","Trần Phi Hải","Hải.TP"
"961","THCS_DocBinhKieu","8","8A1","4","Sang","3","Giáo dục thể chất","Lê Văn Nguyên","Nguyên.LV"
"962","THCS_DocBinhKieu","8","8A1","4","Sang","4","Giáo dục thể chất","Lê Văn Nguyên","Nguyên.LV"
"963","THCS_DocBinhKieu","8","8A1","4","Sang","5","Lịch sử","Lê Thị Kim The","The.LTK"
"964","THCS_DocBinhKieu","8","8A1","5","Sang","1","Vật lí","Nguyễn Thị Thắm","Thắm.NT"
"965","THCS_DocBinhKieu","8","8A1","5","Sang","2","Vật lí","Nguyễn Thị Thắm","Thắm.NT"
"966","THCS_DocBinhKieu","8","8A1","5","Sang","3","Tiếng Anh","Trần Thanh Hậu","Hậu.TT"
"967","THCS_DocBinhKieu","8","8A1","5","Sang","4","Ngữ văn","Lê Thị Hoài An","An.LTH"
"968","THCS_DocBinhKieu","8","8A1","5","Sang","5","Hóa học","Lê Thái Phương","Phương.LT"
"969","THCS_DocBinhKieu","8","8A1","6","Sang","1","Vật lí","Nguyễn Thị Thắm","Thắm.NT"
"970","THCS_DocBinhKieu","8","8A1","6","Sang","2","Âm nhạc","Lê Thị Tuyết Xanh","Xanh.LTT"
"971","THCS_DocBinhKieu","8","8A1","6","Sang","3","Mỹ thuật","Lê Minh Đạt","Đạt.LM"
"972","THCS_DocBinhKieu","8","8A1","6","Sang","4","Địa lí","Nguyễn Thị Kim Đỉnh","Đỉnh.NTK"
"973","THCS_DocBinhKieu","8","8A1","6","Sang","5","Toán học","Nguyễn Thái Hùng","Hùng.NThái"
"974","THCS_DocBinhKieu","8","8A1","7","Sang","1","Toán học","Nguyễn Thái Hùng","Hùng.NThái"
"975","THCS_DocBinhKieu","8","8A1","7","Sang","2","Toán học","Nguyễn Thái Hùng","Hùng.NThái"
"976","THCS_DocBinhKieu","8","8A1","7","Sang","3","Tin học","Bùi Kim Phướng","Phướng.BK"
"977","THCS_DocBinhKieu","8","8A1","7","Sang","4","HĐTNHN (Quy mô lớp)","Nguyễn Thái Hùng","Hùng.NThái"
"978","THCS_DocBinhKieu","8","8A1","7","Sang","5","Sinh hoạt lớp","Nguyễn Thái Hùng","Hùng.NThái"
"979","THCS_TanKieu","8","8A10","2","Sang","1","Chào cờ","Trần Văn Nhuận","Nhuận.TV"
"980","THCS_TanKieu","8","8A10","2","Sang","2","Giáo dục công dân","Nguyễn Mỹ Ngân","Ngân.NM"
"981","THCS_TanKieu","8","8A10","2","Sang","3","Địa lí","Nguyễn Thị Kim Sang","Sang.NTK"
"982","THCS_TanKieu","8","8A10","2","Sang","4","Giáo dục thể chất","Lê Thị Ngọc Điệp","Điệp.LTN"
"983","THCS_TanKieu","8","8A10","2","Sang","5","Giáo dục thể chất","Lê Thị Ngọc Điệp","Điệp.LTN"
"984","THCS_TanKieu","8","8A10","3","Sang","1","Vật lí","Nguyễn Thị Bích Phượng","Phượng.NTB"
"985","THCS_TanKieu","8","8A10","3","Sang","2","Tin học","Lê Phước Hậu","Hậu.LP"
"986","THCS_TanKieu","8","8A10","3","Sang","3","Ngữ văn","Nguyễn Thị Thảo","Thảo.NT"
"987","THCS_TanKieu","8","8A10","3","Sang","4","Ngữ văn","Nguyễn Thị Thảo","Thảo.NT"
"988","THCS_TanKieu","8","8A10","3","Sang","5","Công nghệ","Phan Văn Tặt","Tặt.PV"
"989","THCS_TanKieu","8","8A10","4","Sang","1","Ngữ văn","Nguyễn Thị Thảo","Thảo.NT"
"990","THCS_TanKieu","8","8A10","4","Sang","2","Vật lí","Nguyễn Thị Bích Phượng","Phượng.NTB"
"991","THCS_TanKieu","8","8A10","4","Sang","3","Vật lí","Nguyễn Thị Bích Phượng","Phượng.NTB"
"992","THCS_TanKieu","8","8A10","4","Sang","4","Toán học","Trần Văn Nhuận","Nhuận.TV"
"993","THCS_TanKieu","8","8A10","4","Sang","5","Toán học","Trần Văn Nhuận","Nhuận.TV"
"994","THCS_TanKieu","8","8A10","5","Sang","1","Âm nhạc","Nguyễn Anh Văn","Văn.NA"
"995","THCS_TanKieu","8","8A10","5","Sang","2","Mỹ thuật","Trần Thị Mỹ Quốc","Quốc.TTM"
"996","THCS_TanKieu","8","8A10","5","Sang","3","Lịch sử","Châu Thị Kim Hà","Hà.CTK"
"997","THCS_TanKieu","8","8A10","5","Sang","4","Công nghệ","Phan Văn Tặt","Tặt.PV"
"998","THCS_TanKieu","8","8A10","5","Sang","5","Ngữ văn","Nguyễn Thị Thảo","Thảo.NT"
"999","THCS_TanKieu","8","8A10","6","Sang","1","HĐTNHN (Quy mô lớp)","Phan Văn Tặt","Tặt.PV"
"1000","THCS_TanKieu","8","8A10","6","Sang","2","Tiếng Anh","Lê Minh Thành","Thành.LM"
''')
print("Part 2 written")
