# Part 3 of File 4 (1001 to 1528)
with open('data_csv/timetable_file4_raw.csv', 'a', encoding='utf-8') as f:
    f.write('''"1001","THCS_TanKieu","8","8A10","6","Sang","3","Tiếng Anh","Lê Minh Thành","Thành.LM"
"1002","THCS_TanKieu","8","8A10","6","Sang","4","Hóa học","Nguyễn Thị Lụa","Lụa.NT"
"1003","THCS_TanKieu","8","8A10","6","Sang","5","HĐTNHN (Chuyên đề)","Phan Văn Tặt","Tặt.PV"
"1004","THCS_TanKieu","8","8A10","7","Sang","1","Toán học","Trần Văn Nhuận","Nhuận.TV"
"1005","THCS_TanKieu","8","8A10","7","Sang","2","Toán học","Trần Văn Nhuận","Nhuận.TV"
"1006","THCS_TanKieu","8","8A10","7","Sang","3","Lịch sử","Châu Thị Kim Hà","Hà.CTK"
"1007","THCS_TanKieu","8","8A10","7","Sang","4","Tiếng Anh","Lê Minh Thành","Thành.LM"
"1008","THCS_TanKieu","8","8A10","7","Sang","5","Sinh hoạt lớp","Trần Văn Nhuận","Nhuận.TV"
"1009","THCS_DocBinhKieu","8","8A2","2","Sang","1","Chào cờ","Nguyễn Thị Thùy Dương","Dương.NTT"
"1010","THCS_DocBinhKieu","8","8A2","2","Sang","2","Toán học","Nguyễn Văn Tới","Tới.NV"
"1011","THCS_DocBinhKieu","8","8A2","2","Sang","3","Toán học","Nguyễn Văn Tới","Tới.NV"
"1012","THCS_DocBinhKieu","8","8A2","2","Sang","4","Tiếng Anh","Nguyễn Thị Thùy Dương","Dương.NTT"
"1013","THCS_DocBinhKieu","8","8A2","2","Sang","5","Tiếng Anh","Nguyễn Thị Thùy Dương","Dương.NTT"
"1014","THCS_DocBinhKieu","8","8A2","3","Sang","1","Mỹ thuật","Lê Minh Đạt","Đạt.LM"
"1015","THCS_DocBinhKieu","8","8A2","3","Sang","2","Ngữ văn","Lê Thị Hoài An","An.LTH"
"1016","THCS_DocBinhKieu","8","8A2","3","Sang","3","Hóa học","Nguyễn Thị Kim Ngân","Ngân.NK"
"1017","THCS_DocBinhKieu","8","8A2","3","Sang","4","Công nghệ","Trần Phi Hải","Hải.TP"
"1018","THCS_DocBinhKieu","8","8A2","3","Sang","5","Công nghệ","Trần Phi Hải","Hải.TP"
"1019","THCS_DocBinhKieu","8","8A2","4","Sang","1","Lịch sử","Lê Thị Kim The","The.LTK"
"1020","THCS_DocBinhKieu","8","8A2","4","Sang","2","Lịch sử","Lê Thị Kim The","The.LTK"
"1021","THCS_DocBinhKieu","8","8A2","4","Sang","3","Vật lí","Võ Hoàng Toàn","Toàn.VH"
"1022","THCS_DocBinhKieu","8","8A2","4","Sang","4","Ngữ văn","Lê Thị Hoài An","An.LTH"
"1023","THCS_DocBinhKieu","8","8A2","4","Sang","5","Ngữ văn","Lê Thị Hoài An","An.LTH"
"1024","THCS_DocBinhKieu","8","8A2","5","Sang","1","Giáo dục công dân","Nguyễn Thị Xe","Xe.NT"
"1025","THCS_DocBinhKieu","8","8A2","5","Sang","2","Âm nhạc","Lê Thị Tuyết Xanh","Xanh.LTT"
"1026","THCS_DocBinhKieu","8","8A2","5","Sang","3","Tiếng Anh","Nguyễn Thị Thùy Dương","Dương.NTT"
"1027","THCS_DocBinhKieu","8","8A2","5","Sang","4","Vật lí","Võ Hoàng Toàn","Toàn.VH"
"1028","THCS_DocBinhKieu","8","8A2","5","Sang","5","Vật lí","Võ Hoàng Toàn","Toàn.VH"
"1029","THCS_DocBinhKieu","8","8A2","6","Sang","1","Toán học","Nguyễn Văn Tới","Tới.NV"
"1030","THCS_DocBinhKieu","8","8A2","6","Sang","2","Toán học","Nguyễn Văn Tới","Tới.NV"
"1031","THCS_DocBinhKieu","8","8A2","6","Sang","3","Địa lí","Nguyễn Thị Kim Đỉnh","Đỉnh.NTK"
"1032","THCS_DocBinhKieu","8","8A2","6","Sang","4","Giáo dục thể chất","Lê Văn Nguyên","Nguyên.LV"
"1033","THCS_DocBinhKieu","8","8A2","6","Sang","5","Giáo dục thể chất","Lê Văn Nguyên","Nguyên.LV"
"1034","THCS_DocBinhKieu","8","8A2","7","Sang","1","Tin học","Bùi Kim Phướng","Phướng.BK"
"1035","THCS_DocBinhKieu","8","8A2","7","Sang","2","HĐTNHN (Chuyên đề)","Trần Thị Hậu","Hậu.TTH"
"1036","THCS_DocBinhKieu","8","8A2","7","Sang","3","HĐTNHN (Quy mô lớp)","Nguyễn Thị Thùy Dương","Dương.NTT"
"1037","THCS_DocBinhKieu","8","8A2","7","Sang","4","Ngữ văn","Lê Thị Hoài An","An.LTH"
"1038","THCS_DocBinhKieu","8","8A2","7","Sang","5","Sinh hoạt lớp","Nguyễn Thị Thùy Dương","Dương.NTT"
"1039","THCS_DocBinhKieu","8","8A3","2","Sang","1","Chào cờ","Trần Văn Giang","Giang.TV"
"1040","THCS_DocBinhKieu","8","8A3","2","Sang","2","Hóa học","Lê Thái Phương","Phương.LT"
"1041","THCS_DocBinhKieu","8","8A3","2","Sang","3","Giáo dục thể chất","Lê Văn Nguyên","Nguyên.LV"
"1042","THCS_DocBinhKieu","8","8A3","2","Sang","4","Giáo dục thể chất","Lê Văn Nguyên","Nguyên.LV"
"1043","THCS_DocBinhKieu","8","8A3","2","Sang","5","Mỹ thuật","Lê Minh Đạt","Đạt.LM"
"1044","THCS_DocBinhKieu","8","8A3","3","Sang","1","Toán học","Trần Văn Giang","Giang.TV"
"1045","THCS_DocBinhKieu","8","8A3","3","Sang","2","Địa lí","Nguyễn Thị Kim Đỉnh","Đỉnh.NTK"
"1046","THCS_DocBinhKieu","8","8A3","3","Sang","3","Âm nhạc","Lê Thị Tuyết Xanh","Xanh.LTT"
"1047","THCS_DocBinhKieu","8","8A3","3","Sang","4","Ngữ văn","Lê Thị Thảo Ly","Ly.LTT"
"1048","THCS_DocBinhKieu","8","8A3","3","Sang","5","Ngữ văn","Lê Thị Thảo Ly","Ly.LTT"
"1049","THCS_DocBinhKieu","8","8A3","4","Sang","1","Tiếng Anh","Trần Thanh Hậu","Hậu.TT"
"1050","THCS_DocBinhKieu","8","8A3","4","Sang","2","Lịch sử","Lê Thị Kim The","The.LTK"
"1051","THCS_DocBinhKieu","8","8A3","4","Sang","3","Lịch sử","Lê Thị Kim The","The.LTK"
"1052","THCS_DocBinhKieu","8","8A3","4","Sang","4","Toán học","Trần Văn Giang","Giang.TV"
"1053","THCS_DocBinhKieu","8","8A3","4","Sang","5","Toán học","Trần Văn Giang","Giang.TV"
"1054","THCS_DocBinhKieu","8","8A3","5","Sang","1","Giáo dục công dân","Nguyễn Thị Xe","Xe.NT"
"1055","THCS_DocBinhKieu","8","8A3","5","Sang","2","Ngữ văn","Lê Thị Thảo Ly","Ly.LTT"
"1056","THCS_DocBinhKieu","8","8A3","5","Sang","3","Ngữ văn","Lê Thị Thảo Ly","Ly.LTT"
"1057","THCS_DocBinhKieu","8","8A3","5","Sang","4","Vật lí","Nguyễn Thị Cẩm Nhung","Nhung.NTC"
"1058","THCS_DocBinhKieu","8","8A3","5","Sang","5","Vật lí","Nguyễn Thị Cẩm Nhung","Nhung.NTC"
"1059","THCS_DocBinhKieu","8","8A3","6","Sang","1","Tin học","Bùi Kim Phướng","Phướng.BK"
"1060","THCS_DocBinhKieu","8","8A3","6","Sang","2","Vật lí","Nguyễn Thị Cẩm Nhung","Nhung.NTC"
"1061","THCS_DocBinhKieu","8","8A3","6","Sang","3","Tiếng Anh","Trần Thanh Hậu","Hậu.TT"
"1062","THCS_DocBinhKieu","8","8A3","6","Sang","4","Tiếng Anh","Trần Thanh Hậu","Hậu.TT"
"1063","THCS_DocBinhKieu","8","8A3","6","Sang","5","Công nghệ","Trần Phi Hải","Hải.TP"
"1064","THCS_DocBinhKieu","8","8A3","7","Sang","1","Công nghệ","Trần Phi Hải","Hải.TP"
"1065","THCS_DocBinhKieu","8","8A3","7","Sang","2","Toán học","Trần Văn Giang","Giang.TV"
"1066","THCS_DocBinhKieu","8","8A3","7","Sang","3","HĐTNHN (Quy mô lớp)","Trần Văn Giang","Giang.TV"
"1067","THCS_DocBinhKieu","8","8A3","7","Sang","4","HĐTNHN (Chuyên đề)","Trần Thị Hậu","Hậu.TTH"
"1068","THCS_DocBinhKieu","8","8A3","7","Sang","5","Sinh hoạt lớp","Trần Văn Giang","Giang.TV"
"1069","THCS_DocBinhKieu","8","8A4","2","Sang","1","Chào cờ","Trần Phi Hải","Hải.TP"
"1070","THCS_DocBinhKieu","8","8A4","2","Sang","2","Công nghệ","Trần Phi Hải","Hải.TP"
"1071","THCS_DocBinhKieu","8","8A4","2","Sang","3","Công nghệ","Trần Phi Hải","Hải.TP"
"1072","THCS_DocBinhKieu","8","8A4","2","Sang","4","Mỹ thuật","Lê Minh Đạt","Đạt.LM"
"1073","THCS_DocBinhKieu","8","8A4","2","Sang","5","Âm nhạc","Lê Thị Tuyết Xanh","Xanh.LTT"
"1074","THCS_DocBinhKieu","8","8A4","3","Sang","1","Tiếng Anh","Lê Bá Tuấn","Tuấn.LB"
"1075","THCS_DocBinhKieu","8","8A4","3","Sang","2","Vật lí","Nguyễn Thị Thắm","Thắm.NT"
"1076","THCS_DocBinhKieu","8","8A4","3","Sang","3","Toán học","Trần Văn Giang","Giang.TV"
"1077","THCS_DocBinhKieu","8","8A4","3","Sang","4","Toán học","Trần Văn Giang","Giang.TV"
"1078","THCS_DocBinhKieu","8","8A4","3","Sang","5","Hóa học","Lê Thái Phương","Phương.LT"
"1079","THCS_DocBinhKieu","8","8A4","4","Sang","1","Toán học","Trần Văn Giang","Giang.TV"
"1080","THCS_DocBinhKieu","8","8A4","4","Sang","2","Tiếng Anh","Lê Bá Tuấn","Tuấn.LB"
"1081","THCS_DocBinhKieu","8","8A4","4","Sang","3","Tiếng Anh","Lê Bá Tuấn","Tuấn.LB"
"1082","THCS_DocBinhKieu","8","8A4","4","Sang","4","Ngữ văn","Lê Thị Thảo Ly","Ly.LTT"
"1083","THCS_DocBinhKieu","8","8A4","4","Sang","5","Ngữ văn","Lê Thị Thảo Ly","Ly.LTT"
"1084","THCS_DocBinhKieu","8","8A4","5","Sang","1","Tin học","Bùi Kim Phướng","Phướng.BK"
"1085","THCS_DocBinhKieu","8","8A4","5","Sang","2","Lịch sử","Lê Thị Kim The","The.LTK"
"1086","THCS_DocBinhKieu","8","8A4","5","Sang","3","Toán học","Trần Văn Giang","Giang.TV"
"1087","THCS_DocBinhKieu","8","8A4","5","Sang","4","Giáo dục thể chất","Lê Ngọc Ẩn","Ẩn.LN"
"1088","THCS_DocBinhKieu","8","8A4","5","Sang","5","Giáo dục thể chất","Lê Ngọc Ẩn","Ẩn.LN"
"1089","THCS_DocBinhKieu","8","8A4","6","Sang","1","Giáo dục công dân","Nguyễn Thị Xe","Xe.NT"
"1090","THCS_DocBinhKieu","8","8A4","6","Sang","2","Địa lí","Nguyễn Thị Kim Đỉnh","Đỉnh.NTK"
"1091","THCS_DocBinhKieu","8","8A4","6","Sang","3","Ngữ văn","Lê Thị Thảo Ly","Ly.LTT"
"1092","THCS_DocBinhKieu","8","8A4","6","Sang","4","Vật lí","Nguyễn Thị Thắm","Thắm.NT"
"1093","THCS_DocBinhKieu","8","8A4","6","Sang","5","Vật lí","Nguyễn Thị Thắm","Thắm.NT"
"1094","THCS_DocBinhKieu","8","8A4","7","Sang","1","HĐTNHN (Chuyên đề)","Trần Thị Hậu","Hậu.TTH"
"1095","THCS_DocBinhKieu","8","8A4","7","Sang","2","Lịch sử","Lê Thị Kim The","The.LTK"
"1096","THCS_DocBinhKieu","8","8A4","7","Sang","3","Ngữ văn","Lê Thị Thảo Ly","Ly.LTT"
"1097","THCS_DocBinhKieu","8","8A4","7","Sang","4","HĐTNHN (Quy mô lớp)","Trần Phi Hải","Hải.TP"
"1098","THCS_DocBinhKieu","8","8A4","7","Sang","5","Sinh hoạt lớp","Trần Phi Hải","Hải.TP"
"1099","THCS_DocBinhKieu","8","8A5","2","Sang","1","Chào cờ","Nguyễn Anh Văn","Văn.NA"
"1100","THCS_DocBinhKieu","8","8A5","2","Sang","2","Tin học","Bùi Kim Phướng","Phướng.BK"
"1101","THCS_DocBinhKieu","8","8A5","2","Sang","3","Ngữ văn","Nguyễn Thị Kim Xoa","Xoa.NTK"
"1102","THCS_DocBinhKieu","8","8A5","2","Sang","4","Toán học","Lê Cao Toàn","Toàn.LC"
"1103","THCS_DocBinhKieu","8","8A5","2","Sang","5","Toán học","Lê Cao Toàn","Toàn.LC"
"1104","THCS_DocBinhKieu","8","8A5","3","Sang","1","Vật lí","Võ Hoàng Toàn","Toàn.VH"
"1105","THCS_DocBinhKieu","8","8A5","3","Sang","2","Vật lí","Võ Hoàng Toàn","Toàn.VH"
"1106","THCS_DocBinhKieu","8","8A5","3","Sang","3","Mỹ thuật","Lê Minh Đạt","Đạt.LM"
"1107","THCS_DocBinhKieu","8","8A5","3","Sang","4","Tiếng Anh","Trần Thanh Hậu","Hậu.TT"
"1108","THCS_DocBinhKieu","8","8A5","3","Sang","5","Tiếng Anh","Trần Thanh Hậu","Hậu.TT"
"1109","THCS_DocBinhKieu","8","8A5","4","Sang","1","Hóa học","Lê Thái Phương","Phương.LT"
"1110","THCS_DocBinhKieu","8","8A5","4","Sang","2","Toán học","Lê Cao Toàn","Toàn.LC"
"1111","THCS_DocBinhKieu","8","8A5","4","Sang","3","Toán học","Lê Cao Toàn","Toàn.LC"
"1112","THCS_DocBinhKieu","8","8A5","4","Sang","4","Ngữ văn","Nguyễn Thị Kim Xoa","Xoa.NTK"
"1113","THCS_DocBinhKieu","8","8A5","4","Sang","5","Ngữ văn","Nguyễn Thị Kim Xoa","Xoa.NTK"
"1114","THCS_DocBinhKieu","8","8A5","5","Sang","1","Công nghệ","Trần Phi Hải","Hải.TP"
"1115","THCS_DocBinhKieu","8","8A5","5","Sang","2","Công nghệ","Trần Phi Hải","Hải.TP"
"1116","THCS_DocBinhKieu","8","8A5","5","Sang","3","Ngữ văn","Nguyễn Thị Kim Xoa","Xoa.NTK"
"1117","THCS_DocBinhKieu","8","8A5","5","Sang","4","Lịch sử","Lê Thị Kim The","The.LTK"
"1118","THCS_DocBinhKieu","8","8A5","5","Sang","5","Lịch sử","Lê Thị Kim The","The.LTK"
"1119","THCS_DocBinhKieu","8","8A5","6","Sang","1","Tiếng Anh","Trần Thanh Hậu","Hậu.TT"
"1120","THCS_DocBinhKieu","8","8A5","6","Sang","2","Giáo dục công dân","Nguyễn Thị Xe","Xe.NT"
"1121","THCS_DocBinhKieu","8","8A5","6","Sang","3","Vật lí","Võ Hoàng Toàn","Toàn.VH"
"1122","THCS_DocBinhKieu","8","8A5","6","Sang","4","Giáo dục thể chất","Nguyễn Thanh Hùng","Hùng.NThanh"
"1123","THCS_DocBinhKieu","8","8A5","6","Sang","5","Giáo dục thể chất","Nguyễn Thanh Hùng","Hùng.NThanh"
"1124","THCS_DocBinhKieu","8","8A5","7","Sang","1","Âm nhạc","Nguyễn Anh Văn","Văn.NA"
"1125","THCS_DocBinhKieu","8","8A5","7","Sang","2","Địa lí","Nguyễn Thị Kim Đỉnh","Đỉnh.NTK"
"1126","THCS_DocBinhKieu","8","8A5","7","Sang","3","HĐTNHN (Chuyên đề)","Trần Thị Hậu","Hậu.TTH"
"1127","THCS_DocBinhKieu","8","8A5","7","Sang","4","HĐTNHN (Quy mô lớp)","Nguyễn Anh Văn","Văn.NA"
"1128","THCS_DocBinhKieu","8","8A5","7","Sang","5","Sinh hoạt lớp","Nguyễn Anh Văn","Văn.NA"
"1129","THCS_DocBinhKieu","8","8A6","2","Sang","1","Chào cờ","Nguyễn Quốc Nguyễn","Nguyễn.NQ"
"1130","THCS_DocBinhKieu","8","8A6","2","Sang","2","Giáo dục thể chất","Lê Ngọc Ẩn","Ẩn.LN"
"1131","THCS_DocBinhKieu","8","8A6","2","Sang","3","Giáo dục thể chất","Lê Ngọc Ẩn","Ẩn.LN"
"1132","THCS_DocBinhKieu","8","8A6","2","Sang","4","Công nghệ","Trần Phi Hải","Hải.TP"
"1133","THCS_DocBinhKieu","8","8A6","2","Sang","5","Công nghệ","Trần Phi Hải","Hải.TP"
"1134","THCS_DocBinhKieu","8","8A6","3","Sang","1","Toán học","Nguyễn Quốc Nguyễn","Nguyễn.NQ"
"1135","THCS_DocBinhKieu","8","8A6","3","Sang","2","Toán học","Nguyễn Quốc Nguyễn","Nguyễn.NQ"
"1136","THCS_DocBinhKieu","8","8A6","3","Sang","3","Hóa học","Lê Thái Phương","Phương.LT"
"1137","THCS_DocBinhKieu","8","8A6","3","Sang","4","Địa lí","Nguyễn Thị Kim Đỉnh","Đỉnh.NTK"
"1138","THCS_DocBinhKieu","8","8A6","3","Sang","5","Âm nhạc","Lê Thị Tuyết Xanh","Xanh.LTT"
"1139","THCS_DocBinhKieu","8","8A6","4","Sang","1","Giáo dục công dân","Nguyễn Thị Xe","Xe.NT"
"1140","THCS_DocBinhKieu","8","8A6","4","Sang","2","Ngữ văn","Lê Thị Thảo Ly","Ly.LTT"
"1141","THCS_DocBinhKieu","8","8A6","4","Sang","3","Mỹ thuật","Lê Minh Đạt","Đạt.LM"
"1142","THCS_DocBinhKieu","8","8A6","4","Sang","4","Tiếng Anh","Trần Thanh Hậu","Hậu.TT"
"1143","THCS_DocBinhKieu","8","8A6","4","Sang","5","Tiếng Anh","Trần Thanh Hậu","Hậu.TT"
"1144","THCS_DocBinhKieu","8","8A6","5","Sang","1","Toán học","Nguyễn Quốc Nguyễn","Nguyễn.NQ"
"1145","THCS_DocBinhKieu","8","8A6","5","Sang","2","Toán học","Nguyễn Quốc Nguyễn","Nguyễn.NQ"
"1146","THCS_DocBinhKieu","8","8A6","5","Sang","3","Lịch sử","Lê Thị Kim The","The.LTK"
"1147","THCS_DocBinhKieu","8","8A6","5","Sang","4","Vật lí","Nguyễn Thị Cẩm Nhung","Nhung.NTC"
"1148","THCS_DocBinhKieu","8","8A6","5","Sang","5","Vật lí","Nguyễn Thị Cẩm Nhung","Nhung.NTC"
"1149","THCS_DocBinhKieu","8","8A6","6","Sang","1","Ngữ văn","Lê Thị Thảo Ly","Ly.LTT"
"1150","THCS_DocBinhKieu","8","8A6","6","Sang","2","Ngữ văn","Lê Thị Thảo Ly","Ly.LTT"
"1151","THCS_DocBinhKieu","8","8A6","6","Sang","3","Vật lí","Nguyễn Thị Cẩm Nhung","Nhung.NTC"
"1152","THCS_DocBinhKieu","8","8A6","6","Sang","4","Lịch sử","Lê Thị Kim The","The.LTK"
"1153","THCS_DocBinhKieu","8","8A6","6","Sang","5","Tin học","Bùi Kim Phướng","Phướng.BK"
"1154","THCS_DocBinhKieu","8","8A6","7","Sang","1","Tiếng Anh","Trần Thanh Hậu","Hậu.TT"
"1155","THCS_DocBinhKieu","8","8A6","7","Sang","2","Ngữ văn","Lê Thị Thảo Ly","Ly.LTT"
"1156","THCS_DocBinhKieu","8","8A6","7","Sang","3","HĐTNHN (Chuyên đề)","Trần Thị Hậu","Hậu.TTH"
"1157","THCS_DocBinhKieu","8","8A6","7","Sang","4","HĐTNHN (Quy mô lớp)","Nguyễn Quốc Nguyễn","Nguyễn.NQ"
"1158","THCS_DocBinhKieu","8","8A6","7","Sang","5","Sinh hoạt lớp","Nguyễn Quốc Nguyễn","Nguyễn.NQ"
"1159","THCS_TanKieu","8","8A7","2","Sang","1","Chào cờ","Lê Văn Toàn","Toàn.LV"
"1160","THCS_TanKieu","8","8A7","2","Sang","2","Vật lí","Nguyễn Thị Bích Phượng","Phượng.NTB"
"1161","THCS_TanKieu","8","8A7","2","Sang","3","Vật lí","Nguyễn Thị Bích Phượng","Phượng.NTB"
"1162","THCS_TanKieu","8","8A7","2","Sang","4","Ngữ văn","Nguyễn Thị Thảo","Thảo.NT"
"1163","THCS_TanKieu","8","8A7","2","Sang","5","Ngữ văn","Nguyễn Thị Thảo","Thảo.NT"
"1164","THCS_TanKieu","8","8A7","3","Sang","1","Toán học","Lê Văn Toàn","Toàn.LV"
"1165","THCS_TanKieu","8","8A7","3","Sang","2","Toán học","Lê Văn Toàn","Toàn.LV"
"1166","THCS_TanKieu","8","8A7","3","Sang","3","Tiếng Anh","Lê Minh Thành","Thành.LM"
"1167","THCS_TanKieu","8","8A7","3","Sang","4","Công nghệ","Phan Văn Tặt","Tặt.PV"
"1168","THCS_TanKieu","8","8A7","3","Sang","5","Công nghệ","Phan Văn Tặt","Tặt.PV"
"1169","THCS_TanKieu","8","8A7","4","Sang","1","Tin học","Lê Phước Hậu","Hậu.LP"
"1170","THCS_TanKieu","8","8A7","4","Sang","2","Vật lí","Nguyễn Thị Bích Phượng","Phượng.NTB"
"1171","THCS_TanKieu","8","8A7","4","Sang","3","Mỹ thuật","Trần Thị Mỹ Quốc","Quốc.TTM"
"1172","THCS_TanKieu","8","8A7","4","Sang","4","Giáo dục thể chất","Lê Văn Chính","Chính.LV"
"1173","THCS_TanKieu","8","8A7","4","Sang","5","Giáo dục thể chất","Lê Văn Chính","Chính.LV"
"1174","THCS_TanKieu","8","8A7","5","Sang","1","Toán học","Lê Văn Toàn","Toàn.LV"
"1175","THCS_TanKieu","8","8A7","5","Sang","2","Toán học","Lê Văn Toàn","Toàn.LV"
"1176","THCS_TanKieu","8","8A7","5","Sang","3","Ngữ văn","Nguyễn Thị Thảo","Thảo.NT"
"1177","THCS_TanKieu","8","8A7","5","Sang","4","Hóa học","Nguyễn Thị Lụa","Lụa.NT"
"1178","THCS_TanKieu","8","8A7","5","Sang","5","Âm nhạc","Nguyễn Anh Văn","Văn.NA"
"1179","THCS_TanKieu","8","8A7","6","Sang","1","Tiếng Anh","Lê Minh Thành","Thành.LM"
"1180","THCS_TanKieu","8","8A7","6","Sang","2","Giáo dục công dân","Nguyễn Mỹ Ngân","Ngân.NM"
"1181","THCS_TanKieu","8","8A7","6","Sang","3","Lịch sử","Châu Thị Kim Hà","Hà.CTK"
"1182","THCS_TanKieu","8","8A7","6","Sang","4","Địa lí","Nguyễn Thị Kim Sang","Sang.NTK"
"1183","THCS_TanKieu","8","8A7","6","Sang","5","HĐTNHN (Chuyên đề)","Trần Kim Phương","Phương.TK"
"1184","THCS_TanKieu","8","8A7","7","Sang","1","Lịch sử","Châu Thị Kim Hà","Hà.CTK"
"1185","THCS_TanKieu","8","8A7","7","Sang","2","Tiếng Anh","Lê Minh Thành","Thành.LM"
"1186","THCS_TanKieu","8","8A7","7","Sang","3","Ngữ văn","Nguyễn Thị Thảo","Thảo.NT"
"1187","THCS_TanKieu","8","8A7","7","Sang","4","HĐTNHN (Quy mô lớp)","Lê Văn Toàn","Toàn.LV"
"1188","THCS_TanKieu","8","8A7","7","Sang","5","Sinh hoạt lớp","Lê Văn Toàn","Toàn.LV"
"1189","THCS_TanKieu","8","8A8","2","Sang","1","Chào cờ","Trần Thị Kim Loan","Loan.TTK"
"1190","THCS_TanKieu","8","8A8","2","Sang","2","Toán học","Lê Văn Toàn","Toàn.LV"
"1191","THCS_TanKieu","8","8A8","2","Sang","3","Toán học","Lê Văn Toàn","Toàn.LV"
"1192","THCS_TanKieu","8","8A8","2","Sang","4","Địa lí","Nguyễn Thị Kim Sang","Sang.NTK"
"1193","THCS_TanKieu","8","8A8","2","Sang","5","Tiếng Anh","Lê Thị Ngọc Tuyền","Tuyền.LTN"
"1194","THCS_TanKieu","8","8A8","3","Sang","1","Mỹ thuật","Trần Thị Mỹ Quốc","Quốc.TTM"
"1195","THCS_TanKieu","8","8A8","3","Sang","2","Âm nhạc","Nguyễn Anh Văn","Văn.NA"
"1196","THCS_TanKieu","8","8A8","3","Sang","3","Giáo dục thể chất","Lê Văn Chính","Chính.LV"
"1197","THCS_TanKieu","8","8A8","3","Sang","4","Giáo dục thể chất","Lê Văn Chính","Chính.LV"
"1198","THCS_TanKieu","8","8A8","3","Sang","5","Tin học","Lê Phước Hậu","Hậu.LP"
"1199","THCS_TanKieu","8","8A8","4","Sang","1","Tiếng Anh","Lê Thị Ngọc Tuyền","Tuyền.LTN"
"1200","THCS_TanKieu","8","8A8","4","Sang","2","Tiếng Anh","Lê Thị Ngọc Tuyền","Tuyền.LTN"
"1201","THCS_TanKieu","8","8A8","4","Sang","3","Công nghệ","Phan Văn Tặt","Tặt.PV"
"1202","THCS_TanKieu","8","8A8","4","Sang","4","Vật lí","Nguyễn Thị Bích Phượng","Phượng.NTB"
"1203","THCS_TanKieu","8","8A8","4","Sang","5","Vật lí","Nguyễn Thị Bích Phượng","Phượng.NTB"
"1204","THCS_TanKieu","8","8A8","5","Sang","1","Ngữ văn","Trần Thị Kim Loan","Loan.TTK"
"1205","THCS_TanKieu","8","8A8","5","Sang","2","Ngữ văn","Trần Thị Kim Loan","Loan.TTK"
"1206","THCS_TanKieu","8","8A8","5","Sang","3","Lịch sử","Châu Thị Kim Hà","Hà.CTK"
"1207","THCS_TanKieu","8","8A8","5","Sang","4","Toán học","Lê Văn Toàn","Toàn.LV"
"1208","THCS_TanKieu","8","8A8","5","Sang","5","Toán học","Lê Văn Toàn","Toàn.LV"
"1209","THCS_TanKieu","8","8A8","6","Sang","1","Công nghệ","Phan Văn Tặt","Tặt.PV"
"1210","THCS_TanKieu","8","8A8","6","Sang","2","Vật lí","Nguyễn Thị Bích Phượng","Phượng.NTB"
"1211","THCS_TanKieu","8","8A8","6","Sang","3","Hóa học","Nguyễn Thị Lụa","Lụa.NT"
"1212","THCS_TanKieu","8","8A8","6","Sang","4","Ngữ văn","Trần Thị Kim Loan","Loan.TTK"
"1213","THCS_TanKieu","8","8A8","6","Sang","5","Giáo dục công dân","Nguyễn Mỹ Ngân","Ngân.NM"
"1214","THCS_TanKieu","8","8A8","7","Sang","1","HĐTNHN (Chuyên đề)","Trần Kim Phương","Phương.TK"
"1215","THCS_TanKieu","8","8A8","7","Sang","2","Lịch sử","Châu Thị Kim Hà","Hà.CTK"
"1216","THCS_TanKieu","8","8A8","7","Sang","3","Ngữ văn","Trần Thị Kim Loan","Loan.TTK"
"1217","THCS_TanKieu","8","8A8","7","Sang","4","HĐTNHN (Quy mô lớp)","Trần Thị Kim Loan","Loan.TTK"
"1218","THCS_TanKieu","8","8A8","7","Sang","5","Sinh hoạt lớp","Trần Thị Kim Loan","Loan.TTK"
"1219","THCS_TanKieu","8","8A9","2","Sang","1","Chào cờ","Huỳnh Thị Vân Nhi","Nhi.HTV"
"1220","THCS_TanKieu","8","8A9","2","Sang","2","Tiếng Anh","Lê Minh Thành","Thành.LM"
"1221","THCS_TanKieu","8","8A9","2","Sang","3","Tiếng Anh","Lê Minh Thành","Thành.LM"
"1222","THCS_TanKieu","8","8A9","2","Sang","4","Công nghệ","Phan Văn Tặt","Tặt.PV"
"1223","THCS_TanKieu","8","8A9","2","Sang","5","Công nghệ","Phan Văn Tặt","Tặt.PV"
"1224","THCS_TanKieu","8","8A9","3","Sang","1","Ngữ văn","Huỳnh Thị Vân Nhi","Nhi.HTV"
"1225","THCS_TanKieu","8","8A9","3","Sang","2","Ngữ văn","Huỳnh Thị Vân Nhi","Nhi.HTV"
"1226","THCS_TanKieu","8","8A9","3","Sang","3","Địa lí","Nguyễn Thị Kim Sang","Sang.NTK"
"1227","THCS_TanKieu","8","8A9","3","Sang","4","Tin học","Lê Phước Hậu","Hậu.LP"
"1228","THCS_TanKieu","8","8A9","3","Sang","5","Lịch sử","Châu Thị Kim Hà","Hà.CTK"
"1229","THCS_TanKieu","8","8A9","4","Sang","1","Vật lí","Nguyễn Thị Lụa","Lụa.NT"
"1230","THCS_TanKieu","8","8A9","4","Sang","2","Toán học","Nguyễn Thành Tín","Tín.NT"
"1231","THCS_TanKieu","8","8A9","4","Sang","3","Toán học","Nguyễn Thành Tín","Tín.NT"
"1232","THCS_TanKieu","8","8A9","4","Sang","4","Mỹ thuật","Trần Thị Mỹ Quốc","Quốc.TTM"
"1233","THCS_TanKieu","8","8A9","4","Sang","5","Âm nhạc","Nguyễn Anh Văn","Văn.NA"
"1234","THCS_TanKieu","8","8A9","5","Sang","1","Vật lí","Nguyễn Thị Lụa","Lụa.NT"
"1235","THCS_TanKieu","8","8A9","5","Sang","2","Vật lí","Nguyễn Thị Lụa","Lụa.NT"
"1236","THCS_TanKieu","8","8A9","5","Sang","3","Hóa học","Nguyễn Thị Bích Phượng","Phượng.NTB"
"1237","THCS_TanKieu","8","8A9","5","Sang","4","Ngữ văn","Huỳnh Thị Vân Nhi","Nhi.HTV"
"1238","THCS_TanKieu","8","8A9","5","Sang","5","Ngữ văn","Huỳnh Thị Vân Nhi","Nhi.HTV"
"1239","THCS_TanKieu","8","8A9","6","Sang","1","Lịch sử","Châu Thị Kim Hà","Hà.CTK"
"1240","THCS_TanKieu","8","8A9","6","Sang","2","Tiếng Anh","Lê Minh Thành","Thành.LM"
"1241","THCS_TanKieu","8","8A9","6","Sang","3","Giáo dục thể chất","Lê Thị Ngọc Điệp","Điệp.LTN"
"1242","THCS_TanKieu","8","8A9","6","Sang","4","Giáo dục thể chất","Lê Thị Ngọc Điệp","Điệp.LTN"
"1243","THCS_TanKieu","8","8A9","6","Sang","5","Giáo dục công dân","Nguyễn Mỹ Ngân","Ngân.NM"
"1244","THCS_TanKieu","8","8A9","7","Sang","1","Toán học","Nguyễn Thành Tín","Tín.NT"
"1245","THCS_TanKieu","8","8A9","7","Sang","2","Toán học","Nguyễn Thành Tín","Tín.NT"
"1246","THCS_TanKieu","8","8A9","7","Sang","3","HĐTNHN (Chuyên đề)","Trần Kim Phương","Phương.TK"
"1247","THCS_TanKieu","8","8A9","7","Sang","4","HĐTNHN (Quy mô lớp)","Huỳnh Thị Vân Nhi","Nhi.HTV"
"1248","THCS_TanKieu","8","8A9","7","Sang","5","Sinh hoạt lớp","Huỳnh Thị Vân Nhi","Nhi.HTV"
"1249","THCS_DocBinhKieu","9","9A1","2","Sang","1","Chào cờ","Nguyễn Quốc Tấn","Tấn.NQ"
"1250","THCS_DocBinhKieu","9","9A1","2","Sang","2","Giáo dục công dân","Nguyễn Thị Xe","Xe.NT"
"1251","THCS_DocBinhKieu","9","9A1","2","Sang","3","Tiếng Anh","Trương Thị Ngọc Mai","Mai.TTN"
"1252","THCS_DocBinhKieu","9","9A1","2","Sang","4","Lịch sử và Địa lí","Nguyễn Quốc Tấn","Tấn.NQ"
"1253","THCS_DocBinhKieu","9","9A1","2","Sang","5","Lịch sử và Địa lí","Nguyễn Quốc Tấn","Tấn.NQ"
"1254","THCS_DocBinhKieu","9","9A1","3","Sang","1","Toán học","Nguyễn Thái Hùng","Hùng.NThái"
"1255","THCS_DocBinhKieu","9","9A1","3","Sang","2","Công nghệ","Trần Thị Cẩm","Cẩm.TT"
"1256","THCS_DocBinhKieu","9","9A1","3","Sang","3","Ngữ văn","Phạm Thanh Lâm","Lâm.PT"
"1257","THCS_DocBinhKieu","9","9A1","3","Sang","4","Khoa học tự nhiên","Nguyễn Thị Kim Ngân","Ngân.NK"
"1258","THCS_DocBinhKieu","9","9A1","3","Sang","5","Khoa học tự nhiên","Nguyễn Thị Kim Ngân","Ngân.NK"
"1259","THCS_DocBinhKieu","9","9A1","4","Sang","1","Tiếng Anh","Trương Thị Ngọc Mai","Mai.TTN"
"1260","THCS_DocBinhKieu","9","9A1","4","Sang","2","Tiếng Anh","Trương Thị Ngọc Mai","Mai.TTN"
"1261","THCS_DocBinhKieu","9","9A1","4","Sang","3","Ngữ văn","Phạm Thanh Lâm","Lâm.PT"
"1262","THCS_DocBinhKieu","9","9A1","4","Sang","4","Toán học","Nguyễn Thái Hùng","Hùng.NThái"
"1263","THCS_DocBinhKieu","9","9A1","4","Sang","5","Toán học","Nguyễn Thái Hùng","Hùng.NThái"
"1264","THCS_DocBinhKieu","9","9A1","5","Sang","1","Khoa học tự nhiên","Nguyễn Thị Kim Ngân","Ngân.NK"
"1265","THCS_DocBinhKieu","9","9A1","5","Sang","2","Khoa học tự nhiên","Nguyễn Thị Kim Ngân","Ngân.NK"
"1266","THCS_DocBinhKieu","9","9A1","5","Sang","3","Lịch sử và Địa lí","Nguyễn Quốc Tấn","Tấn.NQ"
"1267","THCS_DocBinhKieu","9","9A1","5","Sang","4","Tin học","Bùi Kim Phướng","Phướng.BK"
"1268","THCS_DocBinhKieu","9","9A1","5","Sang","5","Âm nhạc","Nguyễn Anh Văn","Văn.NA"
"1269","THCS_DocBinhKieu","9","9A1","6","Sang","1","Ngữ văn","Phạm Thanh Lâm","Lâm.PT"
"1270","THCS_DocBinhKieu","9","9A1","6","Sang","2","Ngữ văn","Phạm Thanh Lâm","Lâm.PT"
"1271","THCS_DocBinhKieu","9","9A1","6","Sang","3","Mỹ thuật","Trần Thị Mỹ Quốc","Quốc.TTM"
"1272","THCS_DocBinhKieu","9","9A1","6","Sang","4","Giáo dục thể chất","Nguyễn Thanh Hùng","Hùng.NThanh"
"1273","THCS_DocBinhKieu","9","9A1","6","Sang","5","Giáo dục thể chất","Nguyễn Thanh Hùng","Hùng.NThanh"
"1274","THCS_DocBinhKieu","9","9A1","7","Sang","1","Toán học","Nguyễn Thái Hùng","Hùng.NThái"
"1275","THCS_DocBinhKieu","9","9A1","7","Sang","2","HĐTNHN (Chuyên đề)","Trần Thị Hậu","Hậu.TTH"
"1276","THCS_DocBinhKieu","9","9A1","7","Sang","3","HĐTNHN (Quy mô lớp)","Nguyễn Quốc Tấn","Tấn.NQ"
"1277","THCS_DocBinhKieu","9","9A1","7","Sang","4","Sinh hoạt lớp","Nguyễn Quốc Tấn","Tấn.NQ"
"1278","THCS_DocBinhKieu","9","9A2","2","Sang","1","Chào cờ","Trương Thị Ngọc Mai","Mai.TTN"
"1279","THCS_DocBinhKieu","9","9A2","2","Sang","2","Lịch sử và Địa lí","Nguyễn Quốc Tấn","Tấn.NQ"
"1280","THCS_DocBinhKieu","9","9A2","2","Sang","3","Lịch sử và Địa lí","Nguyễn Quốc Tấn","Tấn.NQ"
"1281","THCS_DocBinhKieu","9","9A2","2","Sang","4","Tiếng Anh","Trương Thị Ngọc Mai","Mai.TTN"
"1282","THCS_DocBinhKieu","9","9A2","2","Sang","5","Tiếng Anh","Trương Thị Ngọc Mai","Mai.TTN"
"1283","THCS_DocBinhKieu","9","9A2","3","Sang","1","Giáo dục thể chất","Nguyễn Thanh Hùng","Hùng.NThanh"
"1284","THCS_DocBinhKieu","9","9A2","3","Sang","2","Giáo dục thể chất","Nguyễn Thanh Hùng","Hùng.NThanh"
"1285","THCS_DocBinhKieu","9","9A2","3","Sang","3","Toán học","Nguyễn Văn Ngoan","Ngoan.NV"
"1286","THCS_DocBinhKieu","9","9A2","3","Sang","4","Khoa học tự nhiên","Lê Thái Phương","Phương.LT"
"1287","THCS_DocBinhKieu","9","9A2","3","Sang","5","Khoa học tự nhiên","Lê Thái Phương","Phương.LT"
"1288","THCS_DocBinhKieu","9","9A2","4","Sang","1","Giáo dục công dân","Nguyễn Thị Xe","Xe.NT"
"1289","THCS_DocBinhKieu","9","9A2","4","Sang","2","Ngữ văn","Phạm Thanh Lâm","Lâm.PT"
"1290","THCS_DocBinhKieu","9","9A2","4","Sang","3","Âm nhạc","Nguyễn Anh Văn","Văn.NA"
"1291","THCS_DocBinhKieu","9","9A2","4","Sang","4","Toán học","Nguyễn Văn Ngoan","Ngoan.NV"
"1292","THCS_DocBinhKieu","9","9A2","4","Sang","5","Toán học","Nguyễn Văn Ngoan","Ngoan.NV"
"1293","THCS_DocBinhKieu","9","9A2","5","Sang","1","Ngữ văn","Phạm Thanh Lâm","Lâm.PT"
"1294","THCS_DocBinhKieu","9","9A2","5","Sang","2","Ngữ văn","Phạm Thanh Lâm","Lâm.PT"
"1295","THCS_DocBinhKieu","9","9A2","5","Sang","3","Công nghệ","Trần Thị Cẩm","Cẩm.TT"
"1296","THCS_DocBinhKieu","9","9A2","5","Sang","4","Khoa học tự nhiên","Lê Thái Phương","Phương.LT"
"1297","THCS_DocBinhKieu","9","9A2","5","Sang","5","Khoa học tự nhiên","Lê Thái Phương","Phương.LT"
"1298","THCS_DocBinhKieu","9","9A2","6","Sang","1","Toán học","Nguyễn Văn Ngoan","Ngoan.NV"
"1299","THCS_DocBinhKieu","9","9A2","6","Sang","2","Tin học","Bùi Kim Phướng","Phướng.BK"
"1300","THCS_DocBinhKieu","9","9A2","6","Sang","3","Tiếng Anh","Trương Thị Ngọc Mai","Mai.TTN"
"1301","THCS_DocBinhKieu","9","9A2","6","Sang","4","Ngữ văn","Phạm Thanh Lâm","Lâm.PT"
"1302","THCS_DocBinhKieu","9","9A2","6","Sang","5","Mỹ thuật","Trần Thị Mỹ Quốc","Quốc.TTM"
"1303","THCS_DocBinhKieu","9","9A2","7","Sang","1","Lịch sử và Địa lí","Nguyễn Quốc Tấn","Tấn.NQ"
"1304","THCS_DocBinhKieu","9","9A2","7","Sang","2","HĐTNHN (Chuyên đề)","Trần Thị Hậu","Hậu.TTH"
"1305","THCS_DocBinhKieu","9","9A2","7","Sang","3","HĐTNHN (Quy mô lớp)","Trương Thị Ngọc Mai","Mai.TTN"
"1306","THCS_DocBinhKieu","9","9A2","7","Sang","4","Sinh hoạt lớp","Trương Thị Ngọc Mai","Mai.TTN"
"1307","THCS_DocBinhKieu","9","9A3","2","Sang","1","Chào cờ","Phạm Thanh Lâm","Lâm.PT"
"1308","THCS_DocBinhKieu","9","9A3","2","Sang","2","Toán học","Lê Cao Toàn","Toàn.LC"
"1309","THCS_DocBinhKieu","9","9A3","2","Sang","3","Giáo dục công dân","Nguyễn Thị Xe","Xe.NT"
"1310","THCS_DocBinhKieu","9","9A3","2","Sang","4","Ngữ văn","Phạm Thanh Lâm","Lâm.PT"
"1311","THCS_DocBinhKieu","9","9A3","2","Sang","5","Ngữ văn","Phạm Thanh Lâm","Lâm.PT"
"1312","THCS_DocBinhKieu","9","9A3","3","Sang","1","Tiếng Anh","Trương Thị Ngọc Mai","Mai.TTN"
"1313","THCS_DocBinhKieu","9","9A3","3","Sang","2","Khoa học tự nhiên","Nguyễn Kim Ngân","Ngân.NK"
"1314","THCS_DocBinhKieu","9","9A3","3","Sang","3","Khoa học tự nhiên","Nguyễn Kim Ngân","Ngân.NK"
"1315","THCS_DocBinhKieu","9","9A3","3","Sang","4","Lịch sử và Địa lí","Trần Phước Hòa","Hòa.TP"
"1316","THCS_DocBinhKieu","9","9A3","3","Sang","5","Lịch sử và Địa lí","Trần Phước Hòa","Hòa.TP"
"1317","THCS_DocBinhKieu","9","9A3","4","Sang","1","Ngữ văn","Phạm Thanh Lâm","Lâm.PT"
"1318","THCS_DocBinhKieu","9","9A3","4","Sang","2","Toán học","Lê Cao Toàn","Toàn.LC"
"1319","THCS_DocBinhKieu","9","9A3","4","Sang","3","Toán học","Lê Cao Toàn","Toàn.LC"
"1320","THCS_DocBinhKieu","9","9A3","4","Sang","4","Âm nhạc","Nguyễn Anh Văn","Văn.NA"
"1321","THCS_DocBinhKieu","9","9A3","4","Sang","5","Mỹ thuật","Trần Thị Mỹ Quốc","Quốc.TTM"
"1322","THCS_DocBinhKieu","9","9A3","5","Sang","1","Công nghệ","Trần Thị Cẩm","Cẩm.TT"
"1323","THCS_DocBinhKieu","9","9A3","5","Sang","2","Tin học","Bùi Kim Phướng","Phướng.BK"
"1324","THCS_DocBinhKieu","9","9A3","5","Sang","3","Giáo dục thể chất","Nguyễn Thanh Hùng","Hùng.NThanh"
"1325","THCS_DocBinhKieu","9","9A3","5","Sang","4","Giáo dục thể chất","Nguyễn Thanh Hùng","Hùng.NThanh"
"1326","THCS_DocBinhKieu","9","9A3","5","Sang","5","Lịch sử và Địa lí","Trần Phước Hòa","Hòa.TP"
"1327","THCS_DocBinhKieu","9","9A3","6","Sang","1","Toán học","Lê Cao Toàn","Toàn.LC"
"1328","THCS_DocBinhKieu","9","9A3","6","Sang","2","Khoa học tự nhiên","Nguyễn Kim Ngân","Ngân.NK"
"1329","THCS_DocBinhKieu","9","9A3","6","Sang","3","Khoa học tự nhiên","Nguyễn Kim Ngân","Ngân.NK"
"1330","THCS_DocBinhKieu","9","9A3","6","Sang","4","Tiếng Anh","Trương Thị Ngọc Mai","Mai.TTN"
"1331","THCS_DocBinhKieu","9","9A3","6","Sang","5","Tiếng Anh","Trương Thị Ngọc Mai","Mai.TTN"
"1332","THCS_DocBinhKieu","9","9A3","7","Sang","1","Ngữ văn","Phạm Thanh Lâm","Lâm.PT"
"1333","THCS_DocBinhKieu","9","9A3","7","Sang","2","HĐTNHN (Chuyên đề)","Trần Thị Hậu","Hậu.TTH"
"1334","THCS_DocBinhKieu","9","9A3","7","Sang","3","HĐTNHN (Quy mô lớp)","Phạm Thanh Lâm","Lâm.PT"
"1335","THCS_DocBinhKieu","9","9A3","7","Sang","4","Sinh hoạt lớp","Phạm Thanh Lâm","Lâm.PT"
"1336","THCS_DocBinhKieu","9","9A4","2","Sang","1","Chào cờ","Trần Phước Hòa","Hòa.TP"
"1337","THCS_DocBinhKieu","9","9A4","2","Sang","2","Mỹ thuật","Trần Thị Mỹ Quốc","Quốc.TTM"
"1338","THCS_DocBinhKieu","9","9A4","2","Sang","3","Ngữ văn","Nguyễn Thị Kim Xoa","Xoa.NTK"
"1339","THCS_DocBinhKieu","9","9A4","2","Sang","4","Toán học","Lê Văn Toàn","Toàn.LV"
"1340","THCS_DocBinhKieu","9","9A4","2","Sang","5","Toán học","Lê Văn Toàn","Toàn.LV"
"1341","THCS_DocBinhKieu","9","9A4","3","Sang","1","Khoa học tự nhiên","Nguyễn Kim Ngân","Ngân.NK"
"1342","THCS_DocBinhKieu","9","9A4","3","Sang","2","Khoa học tự nhiên","Nguyễn Kim Ngân","Ngân.NK"
"1343","THCS_DocBinhKieu","9","9A4","3","Sang","3","Tiếng Anh","Trương Thị Ngọc Mai","Mai.TTN"
"1344","THCS_DocBinhKieu","9","9A4","3","Sang","4","Tin học","Bùi Kim Phướng","Phướng.BK"
"1345","THCS_DocBinhKieu","9","9A4","3","Sang","5","Công nghệ","Trần Thị Cẩm","Cẩm.TT"
"1346","THCS_DocBinhKieu","9","9A4","4","Sang","1","Giáo dục công dân","Nguyễn Thị Xe","Xe.NT"
"1347","THCS_DocBinhKieu","9","9A4","4","Sang","2","Toán học","Lê Văn Toàn","Toàn.LV"
"1348","THCS_DocBinhKieu","9","9A4","4","Sang","3","Lịch sử và Địa lí","Trần Phước Hòa","Hòa.TP"
"1349","THCS_DocBinhKieu","9","9A4","4","Sang","4","Ngữ văn","Nguyễn Thị Kim Xoa","Xoa.NTK"
"1350","THCS_DocBinhKieu","9","9A4","4","Sang","5","Ngữ văn","Nguyễn Thị Kim Xoa","Xoa.NTK"
"1351","THCS_DocBinhKieu","9","9A4","5","Sang","1","Tiếng Anh","Trương Thị Ngọc Mai","Mai.TTN"
"1352","THCS_DocBinhKieu","9","9A4","5","Sang","2","Tiếng Anh","Trương Thị Ngọc Mai","Mai.TTN"
"1353","THCS_DocBinhKieu","9","9A4","5","Sang","3","Lịch sử và Địa lí","Trần Phước Hòa","Hòa.TP"
"1354","THCS_DocBinhKieu","9","9A4","5","Sang","4","Lịch sử và Địa lí","Trần Phước Hòa","Hòa.TP"
"1355","THCS_DocBinhKieu","9","9A4","5","Sang","5","Âm nhạc","Nguyễn Anh Văn","Văn.NA"
"1356","THCS_DocBinhKieu","9","9A4","6","Sang","1","Giáo dục thể chất","Nguyễn Thanh Hùng","Hùng.NThanh"
"1357","THCS_DocBinhKieu","9","9A4","6","Sang","2","Giáo dục thể chất","Nguyễn Thanh Hùng","Hùng.NThanh"
"1358","THCS_DocBinhKieu","9","9A4","6","Sang","3","Khoa học tự nhiên","Nguyễn Kim Ngân","Ngân.NK"
"1359","THCS_DocBinhKieu","9","9A4","6","Sang","4","Khoa học tự nhiên","Nguyễn Kim Ngân","Ngân.NK"
"1360","THCS_DocBinhKieu","9","9A4","6","Sang","5","Toán học","Lê Văn Toàn","Toàn.LV"
"1361","THCS_DocBinhKieu","9","9A4","7","Sang","1","Ngữ văn","Nguyễn Thị Kim Xoa","Xoa.NTK"
"1362","THCS_DocBinhKieu","9","9A4","7","Sang","2","HĐTNHN (Chuyên đề)","Trần Thị Hậu","Hậu.TTH"
"1363","THCS_DocBinhKieu","9","9A4","7","Sang","3","HĐTNHN (Quy mô lớp)","Trần Phước Hòa","Hòa.TP"
"1364","THCS_DocBinhKieu","9","9A4","7","Sang","4","Sinh hoạt lớp","Trần Phước Hòa","Hòa.TP"
"1365","THCS_DocBinhKieu","9","9A5","2","Sang","1","Chào cờ","Võ Hoàng Toàn","Toàn.VH"
"1366","THCS_DocBinhKieu","9","9A5","2","Sang","2","Khoa học tự nhiên","Võ Hoàng Toàn","Toàn.VH"
"1367","THCS_DocBinhKieu","9","9A5","2","Sang","3","Khoa học tự nhiên","Võ Hoàng Toàn","Toàn.VH"
"1368","THCS_DocBinhKieu","9","9A5","2","Sang","4","Lịch sử và Địa lí","Trần Phước Hòa","Hòa.TP"
"1369","THCS_DocBinhKieu","9","9A5","2","Sang","5","Lịch sử và Địa lí","Trần Phước Hòa","Hòa.TP"
"1370","THCS_DocBinhKieu","9","9A5","3","Sang","1","Toán học","Lê Cao Toàn","Toàn.LC"
"1371","THCS_DocBinhKieu","9","9A5","3","Sang","2","Mỹ thuật","Trần Thị Mỹ Quốc","Quốc.TTM"
"1372","THCS_DocBinhKieu","9","9A5","3","Sang","3","Giáo dục công dân","Nguyễn Thị Xe","Xe.NT"
"1373","THCS_DocBinhKieu","9","9A5","3","Sang","4","Giáo dục thể chất","Nguyễn Thanh Hùng","Hùng.NThanh"
"1374","THCS_DocBinhKieu","9","9A5","3","Sang","5","Giáo dục thể chất","Nguyễn Thanh Hùng","Hùng.NThanh"
"1375","THCS_DocBinhKieu","9","9A5","4","Sang","1","Ngữ văn","Lê Thị Thảo Ly","Ly.LTT"
"1376","THCS_DocBinhKieu","9","9A5","4","Sang","2","Ngữ văn","Lê Thị Thảo Ly","Ly.LTT"
"1377","THCS_DocBinhKieu","9","9A5","4","Sang","3","Khoa học tự nhiên","Võ Hoàng Toàn","Toàn.VH"
"1378","THCS_DocBinhKieu","9","9A5","4","Sang","4","Khoa học tự nhiên","Võ Hoàng Toàn","Toàn.VH"
"1379","THCS_DocBinhKieu","9","9A5","4","Sang","5","Tin học","Bùi Kim Phướng","Phướng.BK"
"1380","THCS_DocBinhKieu","9","9A5","5","Sang","1","Toán học","Lê Cao Toàn","Toàn.LC"
"1381","THCS_DocBinhKieu","9","9A5","5","Sang","2","Toán học","Lê Cao Toàn","Toàn.LC"
"1382","THCS_DocBinhKieu","9","9A5","5","Sang","3","Âm nhạc","Nguyễn Anh Văn","Văn.NA"
"1383","THCS_DocBinhKieu","9","9A5","5","Sang","4","Tiếng Anh","Trương Thị Ngọc Mai","Mai.TTN"
"1384","THCS_DocBinhKieu","9","9A5","5","Sang","5","Tiếng Anh","Trương Thị Ngọc Mai","Mai.TTN"
"1385","THCS_DocBinhKieu","9","9A5","6","Sang","1","Công nghệ","Trần Thị Cẩm","Cẩm.TT"
"1386","THCS_DocBinhKieu","9","9A5","6","Sang","2","Toán học","Lê Cao Toàn","Toàn.LC"
"1387","THCS_DocBinhKieu","9","9A5","6","Sang","3","Lịch sử và Địa lí","Trần Phước Hòa","Hòa.TP"
"1388","THCS_DocBinhKieu","9","9A5","6","Sang","4","Ngữ văn","Lê Thị Thảo Ly","Ly.LTT"
"1389","THCS_DocBinhKieu","9","9A5","6","Sang","5","Ngữ văn","Lê Thị Thảo Ly","Ly.LTT"
"1390","THCS_DocBinhKieu","9","9A5","7","Sang","1","Tiếng Anh","Trương Thị Ngọc Mai","Mai.TTN"
"1391","THCS_DocBinhKieu","9","9A5","7","Sang","2","HĐTNHN (Chuyên đề)","Trần Thị Hậu","Hậu.TTH"
"1392","THCS_DocBinhKieu","9","9A5","7","Sang","3","HĐTNHN (Quy mô lớp)","Võ Hoàng Toàn","Toàn.VH"
"1393","THCS_DocBinhKieu","9","9A5","7","Sang","4","Sinh hoạt lớp","Võ Hoàng Toàn","Toàn.VH"
"1394","THCS_TanKieu","9","9A6","2","Sang","1","Chào cờ","Trần Thị Mỹ Quốc","Quốc.TTM"
"1395","THCS_TanKieu","9","9A6","2","Sang","2","Ngữ văn","Trần Thị Kim Loan","Loan.TTK"
"1396","THCS_TanKieu","9","9A6","2","Sang","3","Ngữ văn","Trần Thị Kim Loan","Loan.TTK"
"1397","THCS_TanKieu","9","9A6","2","Sang","4","Toán học","Trần Văn Nhuận","Nhuận.TV"
"1398","THCS_TanKieu","9","9A6","2","Sang","5","Toán học","Trần Văn Nhuận","Nhuận.TV"
"1399","THCS_TanKieu","9","9A6","3","Sang","1","Mỹ thuật","Trần Thị Mỹ Quốc","Quốc.TTM"
"1400","THCS_TanKieu","9","9A6","3","Sang","2","Giáo dục công dân","Nguyễn Mỹ Ngân","Ngân.NM"
"1401","THCS_TanKieu","9","9A6","3","Sang","3","Tiếng Anh","Lê Bá Tuấn","Tuấn.LB"
"1402","THCS_TanKieu","9","9A6","3","Sang","4","Khoa học tự nhiên","Trần Kim Phương","Phương.TK"
"1403","THCS_TanKieu","9","9A6","3","Sang","5","Khoa học tự nhiên","Trần Kim Phương","Phương.TK"
"1404","THCS_TanKieu","9","9A6","4","Sang","1","Toán học","Trần Văn Nhuận","Nhuận.TV"
"1405","THCS_TanKieu","9","9A6","4","Sang","2","Tin học","Lê Phước Hậu","Hậu.LP"
"1406","THCS_TanKieu","9","9A6","4","Sang","3","Công nghệ","Nguyễn Thị Ngọc Diễm","Diễm.NTN"
"1407","THCS_TanKieu","9","9A6","4","Sang","4","Lịch sử và Địa lí","Châu Thị Kim Hà","Hà.CTK"
"1408","THCS_TanKieu","9","9A6","4","Sang","5","Lịch sử và Địa lí","Châu Thị Kim Hà","Hà.CTK"
"1409","THCS_TanKieu","9","9A6","5","Sang","1","Khoa học tự nhiên","Trần Kim Phương","Phương.TK"
"1410","THCS_TanKieu","9","9A6","5","Sang","2","Khoa học tự nhiên","Trần Kim Phương","Phương.TK"
"1411","THCS_TanKieu","9","9A6","5","Sang","3","Lịch sử và Địa lí","Châu Thị Kim Hà","Hà.CTK"
"1412","THCS_TanKieu","9","9A6","5","Sang","4","Tiếng Anh","Lê Bá Tuấn","Tuấn.LB"
"1413","THCS_TanKieu","9","9A6","5","Sang","5","Tiếng Anh","Lê Bá Tuấn","Tuấn.LB"
"1414","THCS_TanKieu","9","9A6","6","Sang","1","Ngữ văn","Trần Thị Kim Loan","Loan.TTK"
"1415","THCS_TanKieu","9","9A6","6","Sang","2","Ngữ văn","Trần Thị Kim Loan","Loan.TTK"
"1416","THCS_TanKieu","9","9A6","6","Sang","3","Toán học","Trần Văn Nhuận","Nhuận.TV"
"1417","THCS_TanKieu","9","9A6","6","Sang","4","Giáo dục thể chất","Lê Văn Chính","Chính.LV"
"1418","THCS_TanKieu","9","9A6","6","Sang","5","Giáo dục thể chất","Lê Văn Chính","Chính.LV"
"1419","THCS_TanKieu","9","9A6","7","Sang","1","Âm nhạc","Nguyễn Anh Văn","Văn.NA"
"1420","THCS_TanKieu","9","9A6","7","Sang","2","HĐTNHN (Chuyên đề)","Trần Kim Phương","Phương.TK"
"1421","THCS_TanKieu","9","9A6","7","Sang","3","HĐTNHN (Quy mô lớp)","Trần Thị Mỹ Quốc","Quốc.TTM"
"1422","THCS_TanKieu","9","9A6","7","Sang","4","Sinh hoạt lớp","Trần Thị Mỹ Quốc","Quốc.TTM"
"1423","THCS_TanKieu","9","9A7","2","Sang","1","Chào cờ","Nguyễn Thị Lụa","Lụa.NT"
"1424","THCS_TanKieu","9","9A7","2","Sang","2","Khoa học tự nhiên","Nguyễn Thị Lụa","Lụa.NT"
"1425","THCS_TanKieu","9","9A7","2","Sang","3","Khoa học tự nhiên","Nguyễn Thị Lụa","Lụa.NT"
"1426","THCS_TanKieu","9","9A7","2","Sang","4","Lịch sử và Địa lí","Châu Thị Kim Hà","Hà.CTK"
"1427","THCS_TanKieu","9","9A7","2","Sang","5","Lịch sử và Địa lí","Châu Thị Kim Hà","Hà.CTK"
"1428","THCS_TanKieu","9","9A7","3","Sang","1","Tiếng Anh","Lê Bá Tuấn","Tuấn.LB"
"1429","THCS_TanKieu","9","9A7","3","Sang","2","Tiếng Anh","Lê Bá Tuấn","Tuấn.LB"
"1430","THCS_TanKieu","9","9A7","3","Sang","3","Giáo dục công dân","Nguyễn Mỹ Ngân","Ngân.NM"
"1431","THCS_TanKieu","9","9A7","3","Sang","4","Toán học","Nguyễn Thành Tín","Tín.NT"
"1432","THCS_TanKieu","9","9A7","3","Sang","5","Toán học","Nguyễn Thành Tín","Tín.NT"
"1433","THCS_TanKieu","9","9A7","4","Sang","1","Ngữ văn","Trần Thị Kim Loan","Loan.TTK"
"1434","THCS_TanKieu","9","9A7","4","Sang","2","Ngữ văn","Trần Thị Kim Loan","Loan.TTK"
"1435","THCS_TanKieu","9","9A7","4","Sang","3","Tin học","Lê Phước Hậu","Hậu.LP"
"1436","THCS_TanKieu","9","9A7","4","Sang","4","Mỹ thuật","Trần Thị Mỹ Quốc","Quốc.TTM"
"1437","THCS_TanKieu","9","9A7","4","Sang","5","Âm nhạc","Nguyễn Anh Văn","Văn.NA"
"1438","THCS_TanKieu","9","9A7","5","Sang","1","Giáo dục thể chất","Lê Văn Chính","Chính.LV"
"1439","THCS_TanKieu","9","9A7","5","Sang","2","Giáo dục thể chất","Lê Văn Chính","Chính.LV"
"1440","THCS_TanKieu","9","9A7","5","Sang","3","Khoa học tự nhiên","Nguyễn Thị Lụa","Lụa.NT"
"1441","THCS_TanKieu","9","9A7","5","Sang","4","Khoa học tự nhiên","Nguyễn Thị Lụa","Lụa.NT"
"1442","THCS_TanKieu","9","9A7","5","Sang","5","Lịch sử và Địa lí","Châu Thị Kim Hà","Hà.CTK"
"1443","THCS_TanKieu","9","9A7","6","Sang","1","Toán học","Nguyễn Thành Tín","Tín.NT"
"1444","THCS_TanKieu","9","9A7","6","Sang","2","Toán học","Nguyễn Thành Tín","Tín.NT"
"1445","THCS_TanKieu","9","9A7","6","Sang","3","Công nghệ","Nguyễn Thị Ngọc Diễm","Diễm.NTN"
"1446","THCS_TanKieu","9","9A7","6","Sang","4","Ngữ văn","Trần Thị Kim Loan","Loan.TTK"
"1447","THCS_TanKieu","9","9A7","6","Sang","5","Tiếng Anh","Lê Bá Tuấn","Tuấn.LB"
"1448","THCS_TanKieu","9","9A7","7","Sang","1","Ngữ văn","Trần Thị Kim Loan","Loan.TTK"
"1449","THCS_TanKieu","9","9A7","7","Sang","2","HĐTNHN (Chuyên đề)","Trần Kim Phương","Phương.TK"
"1450","THCS_TanKieu","9","9A7","7","Sang","3","HĐTNHN (Quy mô lớp)","Nguyễn Thị Lụa","Lụa.NT"
"1451","THCS_TanKieu","9","9A7","7","Sang","4","Sinh hoạt lớp","Nguyễn Thị Lụa","Lụa.NT"
"1452","THCS_TanKieu","9","9A8","2","Sang","1","Chào cờ","Nguyễn Thành Tín","Tín.NT"
"1453","THCS_TanKieu","9","9A8","2","Sang","2","Lịch sử và Địa lí","Châu Thị Kim Hà","Hà.CTK"
"1454","THCS_TanKieu","9","9A8","2","Sang","3","Lịch sử và Địa lí","Châu Thị Kim Hà","Hà.CTK"
"1455","THCS_TanKieu","9","9A8","2","Sang","4","Ngữ văn","Trần Thị Kim Loan","Loan.TTK"
"1456","THCS_TanKieu","9","9A8","2","Sang","5","Ngữ văn","Trần Thị Kim Loan","Loan.TTK"
"1457","THCS_TanKieu","9","9A8","3","Sang","1","Công nghệ","Nguyễn Thị Ngọc Diễm","Diễm.NTN"
"1458","THCS_TanKieu","9","9A8","3","Sang","2","Tin học","Lê Phước Hậu","Hậu.LP"
"1459","THCS_TanKieu","9","9A8","3","Sang","3","Khoa học tự nhiên","Nguyễn Thị Bích Phượng","Phượng.NTB"
"1460","THCS_TanKieu","9","9A8","3","Sang","4","Khoa học tự nhiên","Nguyễn Thị Bích Phượng","Phượng.NTB"
"1461","THCS_TanKieu","9","9A8","3","Sang","5","Toán học","Nguyễn Thành Tín","Tín.NT"
"1462","THCS_TanKieu","9","9A8","4","Sang","1","Tiếng Anh","Lê Bá Tuấn","Tuấn.LB"
"1463","THCS_TanKieu","9","9A8","4","Sang","2","Âm nhạc","Nguyễn Anh Văn","Văn.NA"
"1464","THCS_TanKieu","9","9A8","4","Sang","3","Mỹ thuật","Trần Thị Mỹ Quốc","Quốc.TTM"
"1465","THCS_TanKieu","9","9A8","4","Sang","4","Toán học","Nguyễn Thành Tín","Tín.NT"
"1466","THCS_TanKieu","9","9A8","4","Sang","5","Toán học","Nguyễn Thành Tín","Tín.NT"
"1467","THCS_TanKieu","9","9A8","5","Sang","1","Ngữ văn","Trần Thị Kim Loan","Loan.TTK"
"1468","THCS_TanKieu","9","9A8","5","Sang","2","Ngữ văn","Trần Thị Kim Loan","Loan.TTK"
"1469","THCS_TanKieu","9","9A8","5","Sang","3","Giáo dục công dân","Nguyễn Mỹ Ngân","Ngân.NM"
"1470","THCS_TanKieu","9","9A8","5","Sang","4","Tiếng Anh","Lê Bá Tuấn","Tuấn.LB"
"1471","THCS_TanKieu","9","9A8","5","Sang","5","Tiếng Anh","Lê Bá Tuấn","Tuấn.LB"
"1472","THCS_TanKieu","9","9A8","6","Sang","1","Giáo dục thể chất","Lê Văn Chính","Chính.LV"
"1473","THCS_TanKieu","9","9A8","6","Sang","2","Giáo dục thể chất","Lê Văn Chính","Chính.LV"
"1474","THCS_TanKieu","9","9A8","6","Sang","3","Lịch sử và Địa lí","Châu Thị Kim Hà","Hà.CTK"
"1475","THCS_TanKieu","9","9A8","6","Sang","4","Khoa học tự nhiên","Nguyễn Thị Bích Phượng","Phượng.NTB"
"1476","THCS_TanKieu","9","9A8","6","Sang","5","Khoa học tự nhiên","Nguyễn Thị Bích Phượng","Phượng.NTB"
"1477","THCS_TanKieu","9","9A8","7","Sang","1","Toán học","Nguyễn Thành Tín","Tín.NT"
"1478","THCS_TanKieu","9","9A8","7","Sang","2","HĐTNHN (Chuyên đề)","Trần Kim Phương","Phương.TK"
"1479","THCS_TanKieu","9","9A8","7","Sang","3","HĐTNHN (Quy mô lớp)","Nguyễn Thành Tín","Tín.NT"
"1480","THCS_TanKieu","9","9A8","7","Sang","4","Sinh hoạt lớp","Nguyễn Thành Tín","Tín.NT"
"1481","THCS_TanKieu","9","9A9","2","Sang","1","Chào cờ","Lê Bá Tuấn","Tuấn.LB"
"1482","THCS_TanKieu","9","9A9","2","Sang","2","Ngữ văn","Trần Thị Kim Loan","Loan.TTK"
"1483","THCS_TanKieu","9","9A9","2","Sang","3","Ngữ văn","Trần Thị Kim Loan","Loan.TTK"
"1484","THCS_TanKieu","9","9A9","2","Sang","4","Tiếng Anh","Lê Bá Tuấn","Tuấn.LB"
"1485","THCS_TanKieu","9","9A9","2","Sang","5","Tiếng Anh","Lê Bá Tuấn","Tuấn.LB"
"1486","THCS_TanKieu","9","9A9","3","Sang","1","Khoa học tự nhiên","Nguyễn Thị Bích Phượng","Phượng.NTB"
"1487","THCS_TanKieu","9","9A9","3","Sang","2","Khoa học tự nhiên","Nguyễn Thị Bích Phượng","Phượng.NTB"
"1488","THCS_TanKieu","9","9A9","3","Sang","3","Giáo dục công dân","Nguyễn Mỹ Ngân","Ngân.NM"
"1489","THCS_TanKieu","9","9A9","3","Sang","4","Giáo dục thể chất","Lê Văn Chính","Chính.LV"
"1490","THCS_TanKieu","9","9A9","3","Sang","5","Giáo dục thể chất","Lê Văn Chính","Chính.LV"
"1491","THCS_TanKieu","9","9A9","4","Sang","1","Âm nhạc","Nguyễn Anh Văn","Văn.NA"
"1492","THCS_TanKieu","9","9A9","4","Sang","2","Mỹ thuật","Trần Thị Mỹ Quốc","Quốc.TTM"
"1493","THCS_TanKieu","9","9A9","4","Sang","3","Lịch sử và Địa lí","Châu Thị Kim Hà","Hà.CTK"
"1494","THCS_TanKieu","9","9A9","4","Sang","4","Khoa học tự nhiên","Nguyễn Thị Bích Phượng","Phượng.NTB"
"1495","THCS_TanKieu","9","9A9","4","Sang","5","Khoa học tự nhiên","Nguyễn Thị Bích Phượng","Phượng.NTB"
"1496","THCS_TanKieu","9","9A9","5","Sang","1","Toán học","Lê Văn Toàn","Toàn.LV"
"1497","THCS_TanKieu","9","9A9","5","Sang","2","Toán học","Lê Văn Toàn","Toàn.LV"
"1498","THCS_TanKieu","9","9A9","5","Sang","3","Tiếng Anh","Lê Bá Tuấn","Tuấn.LB"
"1499","THCS_TanKieu","9","9A9","5","Sang","4","Tin học","Lê Phước Hậu","Hậu.LP"
"1500","THCS_TanKieu","9","9A9","5","Sang","5","Công nghệ","Nguyễn Thị Ngọc Diễm","Diễm.NTN"
"1501","THCS_TanKieu","9","9A9","6","Sang","1","Lịch sử và Địa lí","Châu Thị Kim Hà","Hà.CTK"
"1502","THCS_TanKieu","9","9A9","6","Sang","2","Lịch sử và Địa lí","Châu Thị Kim Hà","Hà.CTK"
"1503","THCS_TanKieu","9","9A9","6","Sang","3","Toán học","Lê Văn Toàn","Toàn.LV"
"1504","THCS_TanKieu","9","9A9","6","Sang","4","Toán học","Lê Văn Toàn","Toàn.LV"
"1505","THCS_TanKieu","9","9A9","6","Sang","5","Ngữ văn","Trần Thị Kim Loan","Loan.TTK"
"1506","THCS_TanKieu","9","9A9","7","Sang","1","Ngữ văn","Trần Thị Kim Loan","Loan.TTK"
"1507","THCS_TanKieu","9","9A9","7","Sang","2","HĐTNHN (Chuyên đề)","Trần Kim Phương","Phương.TK"
"1508","THCS_TanKieu","9","9A9","7","Sang","3","HĐTNHN (Quy mô lớp)","Lê Bá Tuấn","Tuấn.LB"
"1509","THCS_TanKieu","9","9A9","7","Sang","4","Sinh hoạt lớp","Lê Bá Tuấn","Tuấn.LB"
"1510","THCS_DocBinhKieu","HoiDong","HoiDong","5","Chieu","3","Họp Hội Đồng","Toàn thể GV","HĐ"
"1511","THCS_DocBinhKieu","HoiDong","HoiDong","5","Chieu","4","Họp Hội Đồng","Toàn thể GV","HĐ"
"1512","THCS_DocBinhKieu","HoiDong","HoiDong","5","Chieu","5","Họp Hội Đồng","Toàn thể GV","HĐ"
"1513","THCS_DocBinhKieu","CM_Toan","CM_Toan","5","Chieu","3","Sinh hoạt CM","Tổ Toán","SHCM"
"1514","THCS_DocBinhKieu","CM_Toan","CM_Toan","5","Chieu","4","Sinh hoạt CM","Tổ Toán","SHCM"
"1515","THCS_DocBinhKieu","CM_Van","CM_Van","5","Chieu","3","Sinh hoạt CM","Tổ Văn","SHCM"
"1516","THCS_DocBinhKieu","CM_Van","CM_Van","5","Chieu","4","Sinh hoạt CM","Tổ Văn","SHCM"
"1517","THCS_DocBinhKieu","CM_Anh","CM_Anh","5","Chieu","3","Sinh hoạt CM","Tổ Anh","SHCM"
"1518","THCS_DocBinhKieu","CM_Anh","CM_Anh","5","Chieu","4","Sinh hoạt CM","Tổ Anh","SHCM"
"1519","THCS_DocBinhKieu","CM_KHTN","CM_KHTN","5","Chieu","3","Sinh hoạt CM","Tổ KHTN","SHCM"
"1520","THCS_DocBinhKieu","CM_KHTN","CM_KHTN","5","Chieu","4","Sinh hoạt CM","Tổ KHTN","SHCM"
"1521","THCS_DocBinhKieu","CM_KHXH","CM_KHXH","5","Chieu","3","Sinh hoạt CM","Tổ KHXH","SHCM"
"1522","THCS_DocBinhKieu","CM_KHXH","CM_KHXH","5","Chieu","4","Sinh hoạt CM","Tổ KHXH","SHCM"
"1523","THCS_DocBinhKieu","CM_SuDiaGDCD","CM_SuDiaGDCD","5","Chieu","3","Sinh hoạt CM","Tổ Sử Địa GDCD","SHCM"
"1524","THCS_DocBinhKieu","CM_SuDiaGDCD","CM_SuDiaGDCD","5","Chieu","4","Sinh hoạt CM","Tổ Sử Địa GDCD","SHCM"
"1525","THCS_DocBinhKieu","CM_TinCN","CM_TinCN","5","Chieu","3","Sinh hoạt CM","Tổ Tin - CN","SHCM"
"1526","THCS_DocBinhKieu","CM_TinCN","CM_TinCN","5","Chieu","4","Sinh hoạt CM","Tổ Tin - CN","SHCM"
"1527","THCS_DocBinhKieu","CM_NKTD","CM_NKTD","5","Chieu","3","Sinh hoạt CM","Tổ Năng khiếu - TD","SHCM"
"1528","THCS_DocBinhKieu","CM_NKTD","CM_NKTD","5","Chieu","4","Sinh hoạt CM","Tổ Năng khiếu - TD","SHCM"
''')
print("Part 3 written!")
